REM INSERTING into CONTRACTOR_COMPANIES;
SET DEFINE OFF;
Insert into "CONTRACTOR_COMPANIES" (ID,NAME,VERSION,LAST_MODIFIED_USER_ID,LAST_MODIFIED_USER_NAME,LAST_MODIFIED_DATE_TIME,LAST_OPERATION_TYPE,EFFECTIVE_START_DATE_TIME,EFFECTIVE_END_DATE_TIME) 
values (1,'Total Transload Services',1,0,null,to_timestamp('30-JAN-2018','DD-MM-YYYY'),1,to_date('30-JAN-2018','DD-MM-YYYY'),to_date('31-DEC-9999','DD-MM-YYYY'));
Insert into "CONTRACTOR_COMPANIES" (ID,NAME,VERSION,LAST_MODIFIED_USER_ID,LAST_MODIFIED_USER_NAME,LAST_MODIFIED_DATE_TIME,LAST_OPERATION_TYPE,EFFECTIVE_START_DATE_TIME,EFFECTIVE_END_DATE_TIME) 
values (2,'Transload Logistics Corp',1,0,null,to_timestamp('30-JAN-2018','DD-MM-YYYY'),1,to_date('30-JAN-2018','DD-MM-YYYY'),to_date('31-DEC-9999','DD-MM-YYYY'));
Insert into "CONTRACTOR_COMPANIES" (ID,NAME,VERSION,LAST_MODIFIED_USER_ID,LAST_MODIFIED_USER_NAME,LAST_MODIFIED_DATE_TIME,LAST_OPERATION_TYPE,EFFECTIVE_START_DATE_TIME,EFFECTIVE_END_DATE_TIME) 
values (3,'Crazy Train Transport Ltd.',1,0,null,to_timestamp('30-JAN-2018','DD-MM-YYYY'),1,to_date('30-JAN-2018','DD-MM-YYYY'),to_date('31-DEC-9999','DD-MM-YYYY'));
Insert into "CONTRACTOR_COMPANIES" (ID,NAME,VERSION,LAST_MODIFIED_USER_ID,LAST_MODIFIED_USER_NAME,LAST_MODIFIED_DATE_TIME,LAST_OPERATION_TYPE,EFFECTIVE_START_DATE_TIME,EFFECTIVE_END_DATE_TIME) 
values (4,'Tri-Line Carries',1,0,null,to_timestamp('30-JAN-2018','DD-MM-YYYY'),1,to_date('30-JAN-2018','DD-MM-YYYY'),to_date('31-DEC-9999','DD-MM-YYYY'));
Insert into "CONTRACTOR_COMPANIES" (ID,NAME,VERSION,LAST_MODIFIED_USER_ID,LAST_MODIFIED_USER_NAME,LAST_MODIFIED_DATE_TIME,LAST_OPERATION_TYPE,EFFECTIVE_START_DATE_TIME,EFFECTIVE_END_DATE_TIME) 
values (5,'Starlight Transport Ltd.',1,0,null,to_timestamp('30-JAN-2018','DD-MM-YYYY'),1,to_date('30-JAN-2018','DD-MM-YYYY'),to_date('31-DEC-9999','DD-MM-YYYY'));
Insert into "CONTRACTOR_COMPANIES" (ID,NAME,VERSION,LAST_MODIFIED_USER_ID,LAST_MODIFIED_USER_NAME,LAST_MODIFIED_DATE_TIME,LAST_OPERATION_TYPE,EFFECTIVE_START_DATE_TIME,EFFECTIVE_END_DATE_TIME) 
values (6,'Renegade Oilfield Services',1,0,null,to_timestamp('30-JAN-2018','DD-MM-YYYY'),1,to_date('30-JAN-2018','DD-MM-YYYY'),to_date('31-DEC-9999','DD-MM-YYYY'));
Insert into "CONTRACTOR_COMPANIES" (ID,NAME,VERSION,LAST_MODIFIED_USER_ID,LAST_MODIFIED_USER_NAME,LAST_MODIFIED_DATE_TIME,LAST_OPERATION_TYPE,EFFECTIVE_START_DATE_TIME,EFFECTIVE_END_DATE_TIME) 
values (7,'Comin'' in Hot Cement Delivery Inc',1,0,null,to_timestamp('30-JAN-2018','DD-MM-YYYY'),1,to_date('30-JAN-2018','DD-MM-YYYY'),to_date('31-DEC-9999','DD-MM-YYYY'));
Insert into "CONTRACTOR_COMPANIES" (ID,NAME,VERSION,LAST_MODIFIED_USER_ID,LAST_MODIFIED_USER_NAME,LAST_MODIFIED_DATE_TIME,LAST_OPERATION_TYPE,EFFECTIVE_START_DATE_TIME,EFFECTIVE_END_DATE_TIME) 
values (8,'Evolve Logistics Inc',1,0,null,to_timestamp('30-JAN-2018','DD-MM-YYYY'),1,to_date('30-JAN-2018','DD-MM-YYYY'),to_date('31-DEC-9999','DD-MM-YYYY'));
Insert into "CONTRACTOR_COMPANIES" (ID,NAME,VERSION,LAST_MODIFIED_USER_ID,LAST_MODIFIED_USER_NAME,LAST_MODIFIED_DATE_TIME,LAST_OPERATION_TYPE,EFFECTIVE_START_DATE_TIME,EFFECTIVE_END_DATE_TIME) 
values (9,'Northwoods Hauling Ltd.',1,0,null,to_timestamp('30-JAN-2018','DD-MM-YYYY'),1,to_date('30-JAN-2018','DD-MM-YYYY'),to_date('31-DEC-9999','DD-MM-YYYY'));
Insert into "CONTRACTOR_COMPANIES" (ID,NAME,VERSION,LAST_MODIFIED_USER_ID,LAST_MODIFIED_USER_NAME,LAST_MODIFIED_DATE_TIME,LAST_OPERATION_TYPE,EFFECTIVE_START_DATE_TIME,EFFECTIVE_END_DATE_TIME) 
values (10,'Fox Bros Trucking',1,0,null,to_timestamp('30-JAN-2018','DD-MM-YYYY'),1,to_date('30-JAN-2018','DD-MM-YYYY'),to_date('31-DEC-9999','DD-MM-YYYY'));
