CREATE TABLE [dbo].[StorageInfo](
	[id] [int] NOT NULL,
	[system_id] [int] IDENTITY(1,1) NOT NULL,
	[version] [int] NULL,
	[modified_user_id] [int] NULL,
	[modified_user_name] [nvarchar](50) NULL,
	[modified_datetime] [datetime2](7) NULL,
	[operation_type] [int] NULL,
	[effective_start_datetime] [datetime2](7) NULL,
	[effective_end_datetime] [datetime2](7) NULL,
	[entity_status] [int] NULL,
	[owner_id] [int] NULL,
	[name] [nvarchar](100) NULL,
	[description] [nvarchar](500) NULL,
	[IsReadyForNext] [bit] NULL,
	[BlendName] [nvarchar](255) NULL,
	[ScaleReading] [float] NULL,
	[JobUniqueId] [nvarchar](255) NULL,
	[JobNumber] [nvarchar](255) NULL,
	[PumpedWithAdds] [float] NULL,
	[PumpedWoAdds] [float] NULL,
	[StorageType] [nvarchar](255) NULL,
	[Remains] [float] NULL,
	[InitialTonnage] [float] NULL
) ON [PRIMARY];

CREATE TABLE [dbo].[PostJobReport](
	[id] [int] NOT NULL,
	[system_id] [int] IDENTITY(1,1) NOT NULL,
	[version] [int] NULL,
	[modified_user_id] [int] NULL,
	[modified_user_name] [nvarchar](50) NULL,
	[modified_datetime] [datetime2](7) NULL,
	[operation_type] [int] NULL,
	[effective_start_datetime] [datetime2](7) NULL,
	[effective_end_datetime] [datetime2](7) NULL,
	[entity_status] [int] NULL,
	[owner_id] [int] NULL,
	[name] [nvarchar](100) NULL,
	[description] [nvarchar](500) NULL,
	[JobUniqueId] [nvarchar](255) NULL,
	[CallSheetNumber] [nvarchar](255) NULL,
	[DownHoleLocation] [nvarchar](255) NULL,
	[RevisedDirection] [nvarchar](255) NULL,
	[JobDate] [datetime2](7) NULL,
	[ClientName] [nvarchar](255) NULL,
	[JobType] [nvarchar](255) NULL,
	[IsDirectionRevised] [bit] NULL,
	[RigName] [nvarchar](255) NULL,
	[SurfaceLocation] [nvarchar](255) NULL,
	[JobNumber] [nvarchar](255) NULL,
	[AdditionalInformation] [nvarchar](255) NULL
) ON [PRIMARY];

CREATE TABLE [dbo].[MaintenanceNote](
	[id] [int] NOT NULL,
	[system_id] [int] IDENTITY(1,1) NOT NULL,
	[version] [int] NULL,
	[modified_user_id] [int] NULL,
	[modified_user_name] [nvarchar](50) NULL,
	[modified_datetime] [datetime2](7) NULL,
	[operation_type] [int] NULL,
	[effective_start_datetime] [datetime2](7) NULL,
	[effective_end_datetime] [datetime2](7) NULL,
	[entity_status] [int] NULL,
	[owner_id] [int] NULL,
	[name] [nvarchar](100) NULL,
	[description] [nvarchar](500) NULL,
	[UnitNumber] [nvarchar](255) NULL,
	[JobNumber] [nvarchar](255) NULL,
	[UnitType] [nvarchar](255) NULL,
	[JobUniqueId] [nvarchar](255) NULL,
	[Notes] [ntext] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY];

CREATE TABLE [dbo].[BlendReport](
	[id] [int] NOT NULL,
	[system_id] [int] IDENTITY(1,1) NOT NULL,
	[version] [int] NULL,
	[modified_user_id] [int] NULL,
	[modified_user_name] [nvarchar](50) NULL,
	[modified_datetime] [datetime2](7) NULL,
	[operation_type] [int] NULL,
	[effective_start_datetime] [datetime2](7) NULL,
	[effective_end_datetime] [datetime2](7) NULL,
	[entity_status] [int] NULL,
	[owner_id] [int] NULL,
	[name] [nvarchar](100) NULL,
	[description] [nvarchar](500) NULL,
	[TotalPumpedVolume] [float] NULL,
	[ExpectedCementTop] [float] NULL,
	[JobUniqueId] [nvarchar](255) NULL
) ON [PRIMARY];

CREATE TABLE [dbo].[BlendConsumption](
	[id] [int] NOT NULL,
	[system_id] [int] IDENTITY(1,1) NOT NULL,
	[version] [int] NULL,
	[modified_user_id] [int] NULL,
	[modified_user_name] [nvarchar](50) NULL,
	[modified_datetime] [datetime2](7) NULL,
	[operation_type] [int] NULL,
	[effective_start_datetime] [datetime2](7) NULL,
	[effective_end_datetime] [datetime2](7) NULL,
	[entity_status] [int] NULL,
	[owner_id] [int] NULL,
	[name] [nvarchar](100) NULL,
	[description] [nvarchar](500) NULL,
	[BlendDescription] [nvarchar](255) NULL,
	[JobIntervalId] [int] NULL,
	[SlurryTemperature] [float] NULL,
	[BlendCategory] [nvarchar](255) NULL,
	[BlendReportid] [int] NULL,
	[BlendReportSystemId] [int] NULL,
	[BlendReportName] [nvarchar](100) NULL,
	[BlendReportDescription] [nvarchar](255) NULL,
	[PumpedVolume] [float] NULL,
	[BulkTemperature] [float] NULL,
	[WaterTemperature] [float] NULL,
	[BlendName] [nvarchar](255) NULL,
	[JobIntervalTypeName] [nvarchar](255) NULL,
	[JobEventNumber] [int] NULL
) ON [PRIMARY];

