# MIX_WATER_REQUIREMENT,SACK_WEIGHT,YIELD
ALTER TABLE  [eservice6].[dbo].[PRG_BLEND_SCTNS] Add	[MIX_WATER_REQUIREMENT] [float] NULL
ALTER TABLE  [eservice6].[dbo].[PRG_BLEND_SCTNS] Add	[SACK_WEIGHT] [float] NULL
ALTER TABLE  [eservice6].[dbo].[PRG_BLEND_SCTNS] Add	[YIELD] [float] NULL

ALTER TABLE  [eservice6].[dbo].[PUMP_BLEND_SCTNS] Add	[MIX_WATER_REQUIREMENT] [float] NULL
ALTER TABLE  [eservice6].[dbo].[PUMP_BLEND_SCTNS] Add	[SACK_WEIGHT] [float] NULL
ALTER TABLE  [eservice6].[dbo].[PUMP_BLEND_SCTNS] Add	[YIELD] [float] NULL

ALTER TABLE  [eservice6].[dbo].[PSPT_BLEND_SCTNS] Add	[MIX_WATER_REQUIREMENT] [float] NULL
ALTER TABLE  [eservice6].[dbo].[PSPT_BLEND_SCTNS] Add	[SACK_WEIGHT] [float] NULL
ALTER TABLE  [eservice6].[dbo].[PSPT_BLEND_SCTNS] Add	[YIELD] [float] NULL