ALTER TABLE [PRG_PUMPING_JOB_SECTIONS] ADD [BHC_WELL_TYPE_ID] [int] NULL;
ALTER TABLE [PRG_PUMPING_JOB_SECTIONS] ADD [BHC_WELL_TYPE_DESCRIPTION] [nvarchar](255) NULL;

ALTER TABLE [PRG_PUMPING_JOB_SECTIONS] ADD [WELL_INFO_WELL_OBJECTIVE_ID] [int] NULL;
ALTER TABLE [PRG_PUMPING_JOB_SECTIONS] ADD [WELL_INFO_WELL_OBJECTIVE_DESCRIPTION] [nvarchar](255) NULL;

ALTER TABLE [PRG_PUMPING_JOB_SECTIONS] ADD [EXECUTION_ORDER] [int] NULL;


ALTER TABLE [PROGRAMS] ADD [WLI_RIG_ID] [int] NULL;
ALTER TABLE [PROGRAMS] ADD [WLI_RIG_NAME] [nvarchar](255) NULL;


-- Run following
update PRG_PUMPING_JOB_SECTIONS set BHC_WELL_TYPE_ID = 0, BHC_WELL_TYPE_DESCRIPTION = 'None';
update PRG_PUMPING_JOB_SECTIONS set WELL_INFO_WELL_OBJECTIVE_ID=0, WELL_INFO_WELL_OBJECTIVE_DESCRIPTION = 'None';

update PROGRAMS set WLI_RIG_ID = 0;
