CREATE TABLE `DC_FLAGS` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`Name`	TEXT NOT NULL UNIQUE,
	`Value`	TEXT NOT NULL,
	`TimeStamp`	TEXT NOT NULL
);

CREATE TABLE `ESE_FLAGS` (
	`Id`	INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`NAME`	TEXT NOT NULL UNIQUE,
	`VALUE`	TEXT NOT NULL,
	`TimeStamp`	TEXT NOT NULL
);