--ALTER TABLE [PRG_PUMPING_JOB_SECTIONS] ADD [PUMPER_COUNT]  [int] NULL;
--ALTER TABLE [PRG_PUMPING_JOB_SECTIONS] ADD [JOB_DURATION]  [int] NULL;
--ALTER TABLE [PRG_PUMPING_JOB_SECTIONS] ADD [PUMPING_DURATION]  [int] NULL;

--ALTER TABLE [CALLSHEET_HEADERS] ADD [JD_PUMPER_COUNT]  [int] NULL;
--ALTER TABLE [CALLSHEET_HEADERS] ADD [JD_JOB_DURATION]  [int] NULL;



--ALTER TABLE [PRG_PUMPING_JOB_SECTIONS] ADD [THIRD_PARTY_ITEMS]  [bit] NULL DEFAULT 0;
--ALTER TABLE [PRG_PUMPING_JOB_SECTIONS] ADD [THIRD_PARTY_TEXT]  [nvarchar(500)] NULL;

