BEGIN TRANSACTION
GO
ALTER TABLE dbo.RPT_HSE_INCIDENT_DTL_SCTNS ADD
	HSE_POTENTIAL_SEVERITY_TYPE_ID int NULL,
	HSE_POTENTIAL_SEVERITY_TYPE_NAME nvarchar(50) NULL
GO
ALTER TABLE dbo.RPT_HSE_INCIDENT_DTL_SCTNS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT