
BEGIN TRANSACTION
GO
ALTER TABLE dbo.RPT_HSE_INFORMATION_SCTNS ADD
	HAS_ANY_QUALITY_OBSERVATIONS_TYPE_ID int NULL,
	HAS_ANY_QUALITY_OBSERVATIONS_TYPE_NAME nvarchar(50) NULL,
	QUALITY_OBSERVATION_TYPE_ID int NULL,
	QUALITY_OBSERVATION_TYPE_NAME nvarchar(50) NULL,
	QUALITY_OBSERVATION_DETAILS nvarchar(2000) NULL
GO
ALTER TABLE dbo.RPT_HSE_INFORMATION_SCTNS SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


