
alter table PUMP_PLUGLOADHD_SCTNS add PLUG_LOADING_HEAD_MANUFACTURER_ID int;
alter table PUMP_PLUGLOADHD_SCTNS add PLUG_LOADING_HEAD_MANUFACTURER_NAME nvarchar(50);
alter table PUMP_PLUGLOADHD_SCTNS add PLUG_LOADING_HEAD_SPECIALTY_ID int;
alter table PUMP_PLUGLOADHD_SCTNS add PLUG_LOADING_HEAD_SPECIALTY_NAME nvarchar(50);
alter table PUMP_PLUGLOADHD_SCTNS add SUPPLIER_ID int;
alter table PUMP_PLUGLOADHD_SCTNS add SUPPLIER_NAME nvarchar(50);


alter table PUMP_TUBULAR_PLUG_SCTNS add PLUG_MANUFACTURER_ID int;
alter table PUMP_TUBULAR_PLUG_SCTNS add PLUG_MANUFACTURER_NAME nvarchar(50);