update BlendChemical set BulkDensity = 1440 where upper(name)='0:1:0 ''A''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1160 where upper(name)='2:1:6 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1320 where upper(name)='Proteus LCS' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1510 where upper(name)='0:1:0 ''C''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1360 where upper(name)='2:1:6 ''G'' (Sask)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1330 where upper(name)='Proteus Pro' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1440 where upper(name)='0:1:0 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1160 where upper(name)='2:1:8 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1250 where upper(name)='RAS II' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1440 where upper(name)='0:1:12 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1360 where upper(name)='2:1:8 ''G'' (Sask)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1010 where upper(name)='SanSeal' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1440 where upper(name)='0:1:2 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1350 where upper(name)='ASC IV' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 720 where upper(name)='SanSeal HT' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1440 where upper(name)='0:1:4 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1420 where upper(name)='Expandomix' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1410 where upper(name)='SSi' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1440 where upper(name)='0:1:6 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1220 where upper(name)='Expandomix HT' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 934.8 where upper(name)='Superlite 13' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1440 where upper(name)='0:1:8 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1280 where upper(name)='Expandomix HT (SK)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 895.6 where upper(name)='Superlite 13 (CDM-5)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1440 where upper(name)='0:1:12 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1420 where upper(name)='Expandomix LWL' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 787 where upper(name)='SUPERLITEmix PRO HT' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1290 where upper(name)='1:1:0 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1520 where upper(name)='Glacial Mix' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 730 where upper(name)='SUPERLITEmix PRO' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1350 where upper(name)='1:1:0 ''G'' (Sask)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1240 where upper(name)='iBond' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1170 where upper(name)='SURFACEmix LW (SK)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1290 where upper(name)='1:1:12 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1200 where upper(name)='iGain (SK)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1190.5 where upper(name)='SURFACEmix LW PRO' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1350 where upper(name)='1:1:12 ''G'' (Sask)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1290 where upper(name)='iGain (AB)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1200 where upper(name)='SURFACEmix LW PRO (SK)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1290 where upper(name)='1:1:2 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1190 where upper(name)='iPrime (AB)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1220 where upper(name)='SURFACEmix PRO' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1350 where upper(name)='1:1:2 ''G'' (Sask)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1250 where upper(name)='iPrime (SK)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1027 where upper(name)='SURFACEmix PRO SL' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1290 where upper(name)='1:1:4 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1190 where upper(name)='LCS 1600' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 710.5 where upper(name)='SURFACEmix SLW' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1350 where upper(name)='1:1:4 ''G'' (Sask)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1410 where upper(name)='LCS 1820' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1370 where upper(name)='SurfLite (SK)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1290 where upper(name)='1:1:6 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1350 where upper(name)='Thermal 40' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1350 where upper(name)='1:1:6 ''G'' (Sask)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1107.5 where upper(name)='LITEmix 1325 (AB)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1340 where upper(name)='Thermal 40 EXP' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1290 where upper(name)='1:1:8 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1052.9 where upper(name)='LITEmix 1325 (SK)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1105 where upper(name)='THERMAmix EC EXP' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1350 where upper(name)='1:1:8 ''G'' (Sask)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1115.8 where upper(name)='LITEmix 1400 (AB)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1210 where upper(name)='THERMAmix LT' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1290 where upper(name)='1:1:12 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1128.4 where upper(name)='LITEmix 1400 (SK)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1100 where upper(name)='THERMAmix SLW' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1160 where upper(name)='2:1:0 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1217 where upper(name)='PRODUCTIONmix 1500 PRO' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1110 where upper(name)='ThixLite HT (AB)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1360 where upper(name)='2:1:0 ''G'' (Sask)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1163.3 where upper(name)='PRODUCTIONmix 1600' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1260 where upper(name)='ThixLite HT (SK)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1160 where upper(name)='2:1:12 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1177.1 where upper(name)='PRODUCTIONmix 1600 (SK)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 999 where upper(name)='SURFACEmix LW PRO SL' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1360 where upper(name)='2:1:12 ''G'' (Sask)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1166 where upper(name)='PRODUCTIONmix 1725' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1719 where upper(name)='LDP-C-0117' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1160 where upper(name)='2:1:2 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1191.1 where upper(name)='PRODUCTIONmix LW' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1360 where upper(name)='2:1:2 ''G'' (Sask)' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1091 where upper(name)='PRODUCTIONmix THX' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1160 where upper(name)='2:1:4 ''G''' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1330 where upper(name)='Proteus Core' and effective_end_datetime > getdate();
update BlendChemical set BulkDensity = 1360 where upper(name)='2:1:4 ''G'' (Sask)' and effective_end_datetime > getdate();