

UPDATE [dbo].[TYPE_VALUES_ConvertedToView] SET [EFFECTIVE_END_DATE_TIME]='2023-05-09 12:00:00.0000000'  WHERE [TYPE_ID] = 84 

INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,9,84,null
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')


INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,10,84,'Producer'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')

INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,11,84,'Injector'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')

INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,12,84,'Disposal'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')

		   
INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,13,84,'Observation'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')

INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,14,84,'Core Hole'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')

INSERT INTO [dbo].[ESERVICE_ALL_TYPES]
           ([ID],[NAME],[VERSION])VALUES(119,'WellObjective',0)
		   
INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,1,119,null
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')


INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,2,119,'Oil'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')


INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,3,119,'Gas'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')


INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,4,119,'Water'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')


INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,5,119,'SAGD'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')


INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,6,119,'Carbon Dioxide'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')

INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,7,119,'CCUS'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')

INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,8,119,'CCS'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')

INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,9,119,'Acid'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')

INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,10,119,'Waste'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')

INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,11,119,'Helium'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')

INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,12,119,'Potash'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')

INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,13,119,'Geothermal'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')

INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,14,119,'Hydrogen'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')

INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,15,119,'Lithium'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')


INSERT INTO [dbo].[ESERVICE_ALL_TYPES]
           ([ID],[NAME],[VERSION])VALUES(125,'RemedialObjective',0)

INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,1,125,null
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')


INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,2,125,'SCVF repair'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')

INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,3,125,'Gas migration repair'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')

INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,4,125,'Abandonment'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')


INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,5,125,'Water shut-off'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')



INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,6,125,'Casing repair'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')



INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,7,125,'Shoe squeeze'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')



INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,8,125,'TOL squeeze'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')


INSERT INTO [dbo].[TYPE_VALUES_ConvertedToView]
           ([ID]
           ,[TYPE_INDEX],[TYPE_ID],[DESCRIPTION]
           ,[STATUS],[VERSION],[LAST_MODIFIED_USER_ID],[LAST_MODIFIED_USER_NAME]
           ,[LAST_MODIFIED_DATE_TIME],[LAST_OPERATION_TYPE],[EFFECTIVE_START_DATE_TIME],[EFFECTIVE_END_DATE_TIME])
     VALUES
           ((SELECT max(id)+1 FROM TYPE_VALUES_ConvertedToView)
           ,9,125,'Zone isolation'
		   ,null,0,0,null
           ,GETDATE(),0,'0001-01-01 00:00:00.0000000','9999-12-31 00:00:00.0000000')