ALTER TABLE PRG_PUMPING_JOB_SECTIONS ADD MANAGED_PRESSURE_CEMENTING nvarchar(15)

ALTER TABLE CALLSHEET_HEADERS ADD TM_MANAGED_PRESSURE_CEMENTING nvarchar(15)

ALTER TABLE PUMPING_SERVICE_REPORTS ADD TM_MANAGED_PRESSURE_CEMENTING nvarchar(15)
