
-- 2019/04/16

CREATE TABLE MasterDataManagement.[dbo].[BonusPosition] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[ServiceLineName] nvarchar(255) NULL ,
[ServiceLineSystemId] int NULL ,
[ServiceLineDescription] nvarchar(255) NULL ,
[ServiceLineid] int NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[CrewPosition] (
[id] int NOT NULL IDENTITY(1,1) ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[CrewSchedule] (
[id] int NOT NULL IDENTITY(1,1) ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[StartTime] datetime2(7) NULL ,
[EndTime] datetime2(7) NULL ,
[RigJobCrewSectionid] int NULL ,
[CrewScheduleTypeid] int NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[CrewScheduleType] (
[id] int NOT NULL IDENTITY(1,1) ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[CrewTruckUnitSection] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[SanjelCrewSystemId] int NULL ,
[TruckUnitid] int NULL ,
[SanjelCrewName] nvarchar(255) NULL ,
[TruckUnitSystemId] int NULL ,
[SanjelCrewid] int NULL ,
[SanjelCrewDescription] nvarchar(255) NULL ,
[TruckUnitDescription] nvarchar(255) NULL ,
[TruckUnitName] nvarchar(255) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[CrewType] (
[id] int NOT NULL IDENTITY(1,1) ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[CrewWorkerSection] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[SanjelCrewName] nvarchar(255) NULL ,
[CrewPositionid] int NULL ,
[SanjelCrewSystemId] int NULL ,
[SanjelCrewid] int NULL ,
[WorkerSystemId] int NULL ,
[Workerid] int NULL ,
[WorkerName] nvarchar(255) NULL ,
[SanjelCrewDescription] nvarchar(255) NULL ,
[WorkerDescription] nvarchar(255) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[Employee] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[MiddleName] nvarchar(255) NULL ,
[ServicePointid] int NULL ,
[ServiceLineName] nvarchar(255) NULL ,
[ServiceLineid] int NULL ,
[EmployeeNumber] nvarchar(255) NULL ,
[ServicePointSystemId] int NULL ,
[PreferedFirstName] nvarchar(255) NULL ,
[FirstName] nvarchar(255) NULL ,
[LastName] nvarchar(255) NULL ,
[ServiceLineSystemId] int NULL ,
[ServicePointName] nvarchar(255) NULL ,
[ServiceLineDescription] nvarchar(255) NULL ,
[ServicePointDescription] nvarchar(255) NULL ,
[BonusPositionid] int NULL ,
[BonusPositionSystemId] int NULL ,
[BonusPositionName] nvarchar(255) NULL ,
[BonusPositionDescription] nvarchar(255) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[RigJobCrewSection] (
[id] int NOT NULL IDENTITY(1,1) ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[RigJobCrewSectionStatusid] int NULL ,
[RigJobid] int NULL ,
[SanjelCrewid] int NULL ,
[SanjelCrewName] nvarchar(255) NULL ,
[SanjelCrewDescription] nvarchar(255) NULL ,
[SanjelCrewSystemId] int NULL ,
[RigJobSystemId] int NULL ,
[RigJobName] nvarchar(255) NULL ,
[RigJobDescription] nvarchar(255) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[RigJobCrewSectionStatus] (
[id] int NOT NULL IDENTITY(1,1) ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[RigJobThirdPartyBulkerCrewSection] (
[id] int NOT NULL IDENTITY(1,1) ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[RigJobName] nvarchar(255) NULL ,
[RigJobSystemId] int NULL ,
[ThirdPartyBulkerCrewName] nvarchar(255) NULL ,
[RigJobCrewSectionStatusid] int NULL ,
[ThirdPartyBulkerCrewid] int NULL ,
[ThirdPartyBulkerCrewDescription] nvarchar(255) NULL ,
[ThirdPartyBulkerCrewSystemId] int NULL ,
[RigJobDescription] nvarchar(255) NULL ,
[RigJobid] int NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[SanjelCrew] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[Notes] nvarchar(255) NULL ,
[WorkingServicePointid] int NULL ,
[HomeServicePointDescription] nvarchar(255) NULL ,
[WorkingServicePointDescription] nvarchar(255) NULL ,
[HomeServicePointid] int NULL ,
[WorkingServicePointSystemId] int NULL ,
[HomeServicePointName] nvarchar(255) NULL ,
[WorkingServicePointName] nvarchar(255) NULL ,
[HomeServicePointSystemId] int NULL ,
[Typeid] int NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[ServiceLine] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[ServicePoint] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[ThirdPartyBulkerCrew] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[ContractorCompanyName] nvarchar(255) NULL ,
[ContractorCompanySystemId] int NULL ,
[ContractorCompanyid] int NULL ,
[ContractorCompanyDescription] nvarchar(255) NULL ,
[SupplierContactName] nvarchar(255) NULL ,
[SupplierContactNumber] nvarchar(255) NULL ,
[Typeid] int NULL ,
[Notes] nvarchar(255) NULL ,
[ThirdPartyUnitNumber] nvarchar(255) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[ThirdPartyBulkerCrewSchedule] (
[id] int NOT NULL IDENTITY(1,1) ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[StartTime] datetime2(7) NULL ,
[EndTime] datetime2(7) NULL ,
[CrewScheduleTypeid] int NULL ,
[RigJobThirdPartyBulkerCrewSectionid] int NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[TruckUnit] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[UnitMainTypeName] nvarchar(255) NULL ,
[ServicePointName] nvarchar(255) NULL ,
[UnitSubTypeName] nvarchar(255) NULL ,
[UnitMainTypeSystemId] int NULL ,
[ServicePointDescription] nvarchar(255) NULL ,
[UnitSubTypeid] int NULL ,
[ServicePointSystemId] int NULL ,
[UnitMainTypeDescription] nvarchar(255) NULL ,
[UnitNumber] nvarchar(255) NULL ,
[UnitMainTypeid] int NULL ,
[UnitSubTypeSystemId] int NULL ,
[ServicePointid] int NULL ,
[UnitSubTypeDescription] nvarchar(255) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[UnitMainType] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[UnitSubType] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[UnitMainTypeDescription] nvarchar(255) NULL ,
[UnitMainTypeName] nvarchar(255) NULL ,
[UnitMainTypeSystemId] int NULL ,
[UnitMainTypeid] int NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[UnitSchedule] (
[id] int NOT NULL IDENTITY(1,1) ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[StartTime] datetime2(7) NULL ,
[EndTime] datetime2(7) NULL ,
[UnitScheduleTypeid] int NULL ,
[TruckUnitDescription] nvarchar(255) NULL ,
[TruckUnitid] int NULL ,
[TruckUnitSystemId] int NULL ,
[TruckUnitName] nvarchar(255) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[UnitScheduleType] (
[id] int NOT NULL IDENTITY(1,1) ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(50) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[WorkerSchedule] (
[id] int NOT NULL IDENTITY(1,1) ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[Workerid] int NULL ,
[WorkerDescription] nvarchar(255) NULL ,
[EndTime] datetime2(7) NULL ,
[WorkerScheduleTypeid] int NULL ,
[WorkerName] nvarchar(255) NULL ,
[StartTime] datetime2(7) NULL ,
[WorkerSystemId] int NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[WorkerScheduleType] (
[id] int NOT NULL IDENTITY(1,1) ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(50) NULL ,
[description] nvarchar(500) NULL 
);



CREATE TABLE MasterDataManagement.[dbo].[Bin] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[BinTypeSystemId] int NULL ,
[HomeServicePointDescription] nvarchar(255) NULL ,
[BinTypeName] nvarchar(255) NULL ,
[BinTypeDescription] nvarchar(255) NULL ,
[BinTypeid] int NULL ,
[HomeServicePointid] int NULL ,
[HomeServicePointName] nvarchar(255) NULL ,
[HomeServicePointSystemId] int NULL ,
[WorkingServicePointDescription] nvarchar(255) NULL ,
[BinStatusDescription] nvarchar(255) NULL ,
[BinStatusName] nvarchar(255) NULL ,
[WorkingServicePointName] nvarchar(255) NULL ,
[BinStatusSystemId] int NULL ,
[BinStatusid] int NULL ,
[WorkingServicePointid] int NULL ,
[WorkingServicePointSystemId] int NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[BinStatus] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[BinType] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[BlendCategory] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[CallSheet] (
[id] int NOT NULL IDENTITY(1,1) ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[ClientCompany] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[BillingAddressProvinceOrStateSystemId] int NULL ,
[BillingAddressPostalCode] nvarchar(255) NULL ,
[BillingAddressStreet3] nvarchar(255) NULL ,
[AddressProvinceOrStateSystemId] int NULL ,
[AddressProvinceOrStateName] nvarchar(255) NULL ,
[AddressProvinceOrStateid] int NULL ,
[BillingAddressStreet4] nvarchar(255) NULL ,
[BillingAddressStreet] nvarchar(255) NULL ,
[SanjelCompanyid] int NULL ,
[SanjelCompanyName] nvarchar(255) NULL ,
[BillingAddressProvinceOrStateDescription] nvarchar(255) NULL ,
[AddressStreet4] nvarchar(255) NULL ,
[AddressStreet3] nvarchar(255) NULL ,
[AddressProvinceOrStateDescription] nvarchar(255) NULL ,
[BillingAddressStreet2] nvarchar(255) NULL ,
[IsCODCustomer] bit NULL ,
[SanjelCompanySystemId] int NULL ,
[ShortName] nvarchar(255) NULL ,
[AddressStreet] nvarchar(255) NULL ,
[BillingAddressCity] nvarchar(255) NULL ,
[BillingAddressProvinceOrStateid] int NULL ,
[AddressCity] nvarchar(255) NULL ,
[AddressPostalCode] nvarchar(255) NULL ,
[BillingAddressProvinceOrStateName] nvarchar(255) NULL ,
[AddressStreet2] nvarchar(255) NULL ,
[SanjelCompanyDescription] nvarchar(255) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[ClientConsultant] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[ClientDescription] nvarchar(255) NULL ,
[WorkShiftid] int NULL ,
[Clientid] int NULL ,
[WorkShiftName] nvarchar(255) NULL ,
[ClientSystemId] int NULL ,
[Email] nvarchar(255) NULL ,
[Cell] nvarchar(255) NULL ,
[Phone2] nvarchar(255) NULL ,
[WorkShiftDescription] nvarchar(255) NULL ,
[ClientName] nvarchar(255) NULL ,
[WorkShiftSystemId] int NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[ContractorCompany] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[Country] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[ISOAlpha2] nvarchar(255) NULL ,
[ISONumber] nvarchar(255) NULL ,
[PercentFuelSurcharge] float(53) NULL ,
[ISOAlpha3] nvarchar(255) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[DrillingCompany] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[BillingAddressPostalCode] nvarchar(255) NULL ,
[BillingAddressProvinceOrStateid] int NULL ,
[AddressCity] nvarchar(255) NULL ,
[BillingAddressStreet4] nvarchar(255) NULL ,
[BillingAddressProvinceOrStateName] nvarchar(255) NULL ,
[BillingAddressStreet3] nvarchar(255) NULL ,
[AddressPostalCode] nvarchar(255) NULL ,
[ShortName] nvarchar(255) NULL ,
[BillingAddressStreet] nvarchar(255) NULL ,
[AddressStreet2] nvarchar(255) NULL ,
[SanjelCompanyid] int NULL ,
[AddressStreet] nvarchar(255) NULL ,
[SanjelCompanySystemId] int NULL ,
[AddressProvinceOrStateName] nvarchar(255) NULL ,
[BillingAddressProvinceOrStateDescription] nvarchar(255) NULL ,
[AddressStreet3] nvarchar(255) NULL ,
[BillingAddressStreet2] nvarchar(255) NULL ,
[AddressProvinceOrStateid] int NULL ,
[SanjelCompanyName] nvarchar(255) NULL ,
[SanjelCompanyDescription] nvarchar(255) NULL ,
[BillingAddressProvinceOrStateSystemId] int NULL ,
[IsCODCustomer] bit NULL ,
[AddressProvinceOrStateDescription] nvarchar(255) NULL ,
[BillingAddressCity] nvarchar(255) NULL ,
[AddressProvinceOrStateSystemId] int NULL ,
[AddressStreet4] nvarchar(255) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[JobLifeStatus] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[JobType] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[ServiceLineDescription] nvarchar(255) NULL ,
[ServiceLineSystemId] int NULL ,
[ServiceLineid] int NULL ,
[ServiceLineName] nvarchar(255) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[ProductHaul] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[CrewSystemId] int NULL ,
[ProductHaulLifeStatusName] nvarchar(255) NULL ,
[Crewid] int NULL ,
[IsGoWithCrew] bit NULL ,
[IsThirdParty] bit NULL ,
[ProductHaulLifeStatusid] int NULL ,
[TractorUnitName] nvarchar(255) NULL ,
[Comments] nvarchar(255) NULL ,
[BulkUnitDescription] nvarchar(255) NULL ,
[TractorUnitid] int NULL ,
[ThirdPartyUnitNumber] nvarchar(255) NULL ,
[Driver2SystemId] int NULL ,
[Driver2Name] nvarchar(255) NULL ,
[BulkUnitid] int NULL ,
[ProductHaulLifeStatusSystemId] int NULL ,
[DriverDescription] nvarchar(255) NULL ,
[BulkUnitSystemId] int NULL ,
[CrewName] nvarchar(255) NULL ,
[TractorUnitSystemId] int NULL ,
[ContractorCompanySystemId] int NULL ,
[Driverid] int NULL ,
[ContractorCompanyDescription] nvarchar(255) NULL ,
[DriverSystemId] int NULL ,
[DriverName] nvarchar(255) NULL ,
[SupplierContactName] nvarchar(255) NULL ,
[TractorUnitDescription] nvarchar(255) NULL ,
[BulkUnitName] nvarchar(255) NULL ,
[ContractorCompanyName] nvarchar(255) NULL ,
[SupplierContactNumber] nvarchar(255) NULL ,
[CrewDescription] nvarchar(255) NULL ,
[ProductHaulLifeStatusDescription] nvarchar(255) NULL ,
[ContractorCompanyid] int NULL ,
[Driver2Description] nvarchar(255) NULL ,
[Driver2id] int NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[ProductHaulLoad] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[OnLocationTime] datetime2(7) NULL ,
[BlendSectionId] int NULL ,
[JobTypeName] nvarchar(255) NULL ,
[JobDate] datetime2(7) NULL ,
[JobTypeSystemId] int NULL ,
[BlendCategorySystemId] int NULL ,
[TotalBlendWeight] float(53) NULL ,
[BlendChemicalName] nvarchar(255) NULL ,
[JobTypeDescription] nvarchar(255) NULL ,
[CustomerSystemId] int NULL ,
[ServicePointDescription] nvarchar(255) NULL ,
[ProductHaulid] int NULL ,
[BlendCategoryName] nvarchar(255) NULL ,
[ServicePointName] nvarchar(255) NULL ,
[CustomerName] nvarchar(255) NULL ,
[ExpectedOnLocationTime] datetime2(7) NULL ,
[ProductHaulSystemId] int NULL ,
[BlendCategoryid] int NULL ,
[Comments] nvarchar(255) NULL ,
[BlendChemicalid] int NULL ,
[Binid] int NULL ,
[ServicePointid] int NULL ,
[BlendCategoryDescription] nvarchar(255) NULL ,
[BinDescription] nvarchar(255) NULL ,
[MixWater] float(53) NULL ,
[ProductHaulLoadLifeStatusDescription] nvarchar(255) NULL ,
[BlendChemicalDescription] nvarchar(255) NULL ,
[CallSheetNumber] int NULL ,
[ProductHaulLoadLifeStatusSystemId] int NULL ,
[ServicePointSystemId] int NULL ,
[CustomerDescription] nvarchar(255) NULL ,
[BlendChemicalSystemId] int NULL ,
[IsTotalBlendTonnage] bit NULL ,
[BinName] nvarchar(255) NULL ,
[LoadSheetSerialNumber] nvarchar(255) NULL ,
[ProductHaulLoadLifeStatusid] int NULL ,
[WellLocation] nvarchar(255) NULL ,
[BinSystemId] int NULL ,
[ProductHaulName] nvarchar(255) NULL ,
[IsGoWithCrew] bit NULL ,
[Customerid] int NULL ,
[ProductHaulLoadLifeStatusName] nvarchar(255) NULL ,
[ProductHaulDescription] nvarchar(255) NULL ,
[BaseBlendWeight] float(53) NULL ,
[JobTypeid] int NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[ProductHaulLoadStatus] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[ProductHaulStatus] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[ProductLoadSection] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[ProductHaulLoadid] int NULL ,
[IsFromBase] bit NULL ,
[BlendChemicalName] nvarchar(255) NULL ,
[BlendAdditiveMeasureUnitName] nvarchar(255) NULL ,
[ProductHaulLoadName] nvarchar(255) NULL ,
[BlendChemicalid] int NULL ,
[RequiredAmount] float(53) NULL ,
[BlendAdditiveMeasureUnitDescription] nvarchar(255) NULL ,
[ProductHaulLoadSystemId] int NULL ,
[BlendAdditiveMeasureUnitid] int NULL ,
[AdditiveBlendMethodName] nvarchar(255) NULL ,
[NumberOfBags] float(53) NULL ,
[BagSize] float(53) NULL ,
[BlendChemicalSystemId] int NULL ,
[AdditiveBlendMethodid] int NULL ,
[BlendChemicalDescription] nvarchar(255) NULL ,
[ProductHaulLoadDescription] nvarchar(255) NULL ,
[AdditiveBlendMethodDescription] nvarchar(255) NULL ,
[LoadedAmount] float(53) NULL ,
[AdditiveBlendMethodSystemId] int NULL ,
[BlendAdditiveMeasureUnitSystemId] int NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[ProvinceOrState] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[CountryDescription] nvarchar(255) NULL ,
[CountryName] nvarchar(255) NULL ,
[Code] nvarchar(255) NULL ,
[CountrySystemId] int NULL ,
[Countryid] int NULL ,
[Capital] nvarchar(255) NULL ,
[PercentSalesSurcharge] float(53) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[Rig] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[IsTopDrive] bit NULL ,
[ThreadTypeName] nvarchar(255) NULL ,
[ThreadTypeSystemId] int NULL ,
[Sizeid] int NULL ,
[StatusDescription] nvarchar(255) NULL ,
[DrillingCompanyid] int NULL ,
[SizeDescription] nvarchar(255) NULL ,
[SizeName] nvarchar(255) NULL ,
[RigSizeSystemId] int NULL ,
[ThreadTypeid] int NULL ,
[DrillingCompanyName] nvarchar(255) NULL ,
[RigNumber] nvarchar(255) NULL ,
[RigSizeDescription] nvarchar(255) NULL ,
[DrillingCompanySystemId] int NULL ,
[StatusName] nvarchar(255) NULL ,
[StatusSystemId] int NULL ,
[IsServiceRig] bit NULL ,
[SizeSystemId] int NULL ,
[Statusid] int NULL ,
[IsProjectRig] bit NULL ,
[RigSizeName] nvarchar(255) NULL ,
[DrillingCompanyDescription] nvarchar(255) NULL ,
[ThreadTypeDescription] nvarchar(255) NULL ,
[RigSizeid] int NULL ,
[IsDeleted] bit NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[RigBinSection] (
[id] int NOT NULL IDENTITY(1,1) ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[BinSystemId] int NULL ,
[BinDescription] nvarchar(255) NULL ,
[RigDescription] nvarchar(255) NULL ,
[RigName] nvarchar(255) NULL ,
[Rigid] int NULL ,
[RigSystemId] int NULL ,
[BinName] nvarchar(255) NULL ,
[Binid] int NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[RigJob] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[WellLocation] nvarchar(255) NULL ,
[ClientConsultant1id] int NULL ,
[WellLocationTypeName] nvarchar(255) NULL ,
[IsProjectRig] bit NULL ,
[JobLifeStatusName] nvarchar(255) NULL ,
[JobLifeStatusSystemId] int NULL ,
[ServicePointName] nvarchar(255) NULL ,
[CallSheetId] int NULL ,
[IsListed] bit NULL ,
[ServicePointSystemId] int NULL ,
[IsDownholeLocation] bit NULL ,
[ClientCompanyid] int NULL ,
[JobNumber] int NULL ,
[RigStatusid] int NULL ,
[RigName] nvarchar(255) NULL ,
[WellLocationTypeid] int NULL ,
[WellLocationTypeDescription] nvarchar(255) NULL ,
[JobTypeDescription] nvarchar(255) NULL ,
[IsHighProfile] bit NULL ,
[Directions] nvarchar(1000) NULL ,
[IsNeedBins] bit NULL ,
[RigStatusName] nvarchar(255) NULL ,
[ProgramId] nvarchar(255) NULL ,
[JobLifeStatusDescription] nvarchar(255) NULL ,
[Rigid] int NULL ,
[RigStatusSystemId] int NULL ,
[JobTypeName] nvarchar(255) NULL ,
[Notes] nvarchar(500) NULL ,
[SurfaceLocation] nvarchar(255) NULL ,
[ClientCompanySystemId] int NULL ,
[JobDateTime] datetime2(7) NULL ,
[JobUniqueId] nvarchar(255) NULL ,
[WellLocationTypeSystemId] int NULL ,
[IsServiceRig] bit NULL ,
[ServicePointid] int NULL ,
[JobTypeid] int NULL ,
[CallSheetNumber] int NULL ,
[ClientConsultant2id] int NULL ,
[JobLifeStatusid] int NULL ,
[ClientCompanyName] nvarchar(255) NULL ,
[ClientConsultant2Description] nvarchar(255) NULL ,
[ServicePointDescription] nvarchar(255) NULL ,
[ClientConsultant2Name] nvarchar(255) NULL ,
[ClientConsultant1Name] nvarchar(255) NULL ,
[IsCoDCleared] bit NULL ,
[JobTypeSystemId] int NULL ,
[RigStatusDescription] nvarchar(255) NULL ,
[JobAlertId] int NULL ,
[ClientConsultant1Description] nvarchar(255) NULL ,
[ClientConsultant2SystemId] int NULL ,
[RigSystemId] int NULL ,
[ClientCompanyDescription] nvarchar(255) NULL ,
[ClientConsultant1SystemId] int NULL ,
[RigDescription] nvarchar(255) NULL ,
[ClientCompanyShortName] nvarchar(255) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[RigSize] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[Value] float(53) NULL ,
[Unitid] int NULL ,
[UnitSystemId] int NULL ,
[UnitName] nvarchar(255) NULL ,
[UnitDescription] nvarchar(255) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[RigSizeType] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[RigStatus] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[SanjelCompany] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL ,
[CountryName] nvarchar(255) NULL ,
[CountrySystemId] int NULL ,
[Countryid] int NULL ,
[CountryDescription] nvarchar(255) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[ShiftType] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[ThreadType] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[UnitOfMeasure] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[modified_user_name] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[description] nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[PrimaryUnitOfMeasureSystemId] int NULL ,
[UnitOfMeasureTypeDescription] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[PrimaryUnitOfMeasureDescription] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[UnitOfMeasureSystemOfUnitsDescription] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[UnitOfMeasureSystemOfUnitsid] int NULL ,
[UnitOfMeasureTypeName] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[UnitOfMeasureSystemOfUnitsSystemId] int NULL ,
[UnitOfMeasureTypeSystemId] int NULL ,
[UnitOfMeasureSystemOfUnitsName] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[BaseMultiplier] int NULL ,
[IsUseBaseMultiplier] bit NULL ,
[SecondaryUnitOfMeasureName] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[SecondaryUnitOfMeasureid] int NULL ,
[UnitOfMeasureTypeid] int NULL ,
[PrimaryUnitOfMeasureName] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[IsCompositeUnit] bit NULL ,
[SecondaryUnitOfMeasureSystemId] int NULL ,
[SecondaryUnitOfMeasureDescription] nvarchar(255) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[PrimaryUnitOfMeasureid] int NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[UnitOfMeasureSystemOfUnits] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[modified_user_name] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[description] nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[UnitOfMeasureType] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[modified_user_name] nvarchar(50) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) COLLATE SQL_Latin1_General_CP1_CI_AS NULL ,
[description] nvarchar(500) COLLATE SQL_Latin1_General_CP1_CI_AS NULL 
);

CREATE TABLE MasterDataManagement.[dbo].[WellLocationType] (
[id] int NOT NULL ,
[system_id] int NOT NULL IDENTITY(1,1) ,
[version] int NULL ,
[modified_user_id] nvarchar(50) NULL ,
[modified_user_name] nvarchar(50) NULL ,
[modified_datetime] datetime2(7) NULL ,
[operation_type] int NULL ,
[effective_start_datetime] datetime2(7) NULL ,
[effective_end_datetime] datetime2(7) NULL ,
[entity_status] int NULL ,
[owner_id] int NULL ,
[name] nvarchar(100) NULL ,
[description] nvarchar(500) NULL 
);


