USE [eservice6]
GO

/****** Object:  Table [dbo].[JOBS]    Script Date: 5/25/2020 3:04:02 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PLC_PACK](
	[ID] [int] NOT NULL,
	[STATUS_ID] [int] NULL,
	[JOB_NUMBER] [nvarchar](50) NULL,
	[UNIQUE_ID] [nvarchar](100) NULL,
	[CLIENT_VERSION_STAMP] [nvarchar](20) NULL,
	[CLIENT_SYSTEM_STAMP] [nvarchar](20) NULL,
	[GENERATED_BY] [nvarchar](100) NULL,
	[GENERATED_DATE_TIME] [datetime2](7) NULL,
	[TIME_SENT_TO_SERVER] [datetime2](7) NULL,
	[TIME_CREATED_ON_SERVER] [datetime2](7) NULL,
	[VERSION] [int] NULL,
	[LAST_MODIFIED_USER_ID] [int] NULL,
	[LAST_MODIFIED_USER_NAME] [nvarchar](150) NULL,
	[LAST_MODIFIED_DATE_TIME] [datetime2](7) NOT NULL,
	[LAST_OPERATION_TYPE] [int] NULL,
	[EFFECTIVE_START_DATE_TIME] [datetime2](7) NULL,
	[EFFECTIVE_END_DATE_TIME] [datetime2](7) NOT NULL,
 CONSTRAINT [PLC_PACK_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [PLC_PACK_UNIQUE_ID_UK] UNIQUE NONCLUSTERED 
(
	[UNIQUE_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PLC_PACK] ADD  DEFAULT ((0)) FOR [VERSION]
GO

ALTER TABLE [dbo].[PLC_PACK] ADD  DEFAULT ((0)) FOR [LAST_MODIFIED_USER_ID]
GO

ALTER TABLE [dbo].[PLC_PACK] ADD  DEFAULT ('') FOR [LAST_MODIFIED_USER_NAME]
GO

ALTER TABLE [dbo].[PLC_PACK] ADD  DEFAULT (sysdatetimeoffset()) FOR [LAST_MODIFIED_DATE_TIME]
GO

ALTER TABLE [dbo].[PLC_PACK] ADD  DEFAULT ((0)) FOR [LAST_OPERATION_TYPE]
GO

ALTER TABLE [dbo].[PLC_PACK] ADD  DEFAULT (CONVERT([varchar](12),'1753-01-01',(105))) FOR [EFFECTIVE_START_DATE_TIME]
GO

ALTER TABLE [dbo].[PLC_PACK] ADD  DEFAULT (CONVERT([varchar](12),'9999-12-31',(105))) FOR [EFFECTIVE_END_DATE_TIME]
GO

ALTER TABLE [dbo].[PLC_PACK]  ADD CONSTRAINT [CHECK_LAST_MODIFIED_DATE_TIME_NOT_NULL] CHECK ([LAST_MODIFIED_DATE_TIME] IS NOT NULL)
GO

ALTER TABLE [dbo].[PLC_PACK] CHECK CONSTRAINT [CHECK_LAST_MODIFIED_DATE_TIME_NOT_NULL]
GO

ALTER TABLE [dbo].[PLC_PACK]  WITH CHECK ADD  CONSTRAINT [CHECK_LAST_EFFECTIVE_END_DATE_TIME_NOT_NULL] CHECK  (([EFFECTIVE_END_DATE_TIME] IS NOT NULL))
GO

ALTER TABLE [dbo].[PLC_PACK] CHECK CONSTRAINT [CHECK_LAST_EFFECTIVE_END_DATE_TIME_NOT_NULL]
GO


