USE [eservice6]
GO

/****** Object:  Table [dbo].[RPT_UPLOAD_DOCUMENT_SCTNS]    Script Date: 5/25/2020 3:21:43 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[PLC_UPLOAD_DOCUMENT_SCTNS](
	[ID] [int] NOT NULL,
	[ROOT_ID] [int] NULL,
	[FILE_NAME] [nvarchar](200) NULL,
	[FILE_TYPE_ID] [int] NULL,
	[FILE_TYPE_CATEGORY] [int] NULL,
	[FILE_TYPE_NAME] [nvarchar](50) NULL,
	[LAST_MODIFIED_DATE_TIME] [datetime2](7) NULL,
	[DESCRIPTION] [nvarchar](200) NULL,
	[LOCAL_FILE_PATH] [nvarchar](300) NULL,
	[PRINT_FLAG] [bit] NULL,
	[UPLOADED_DATE_TIME] [datetime2](7) NULL,
	[UPLOADED_BY_EMP_ID] [int] NULL,
	[VERSION] [int] NULL,
	[STATUS] [int] NULL,
	[PARENT_UNIQUE_ID] [nvarchar](100) NULL,
 CONSTRAINT [PLC_UPLOAD_DOCUMENT_SCTNS_PK] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[PLC_UPLOAD_DOCUMENT_SCTNS] ADD  DEFAULT ((0)) FOR [VERSION]
GO

ALTER TABLE [dbo].[PLC_UPLOAD_DOCUMENT_SCTNS]  WITH CHECK ADD  CONSTRAINT [PLC_UPLOAD_DOC_SCTNS_RP_ID_FK] FOREIGN KEY([ROOT_ID])
REFERENCES [dbo].[PLC_PACK] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PLC_UPLOAD_DOCUMENT_SCTNS] CHECK CONSTRAINT [PLC_UPLOAD_DOC_SCTNS_RP_ID_FK]
GO


