http://localhost:44703/DataCleanUp/SetScheduledShippingLoadSheetOnLocationForCompletedJob

http://localhost:44703/DataCleanUp/SetScheduledProductHaulLoadOnLocationByShippingLoadSheetStatus

http://localhost:44703/DataCleanUp/SetCompletedBlendRequestOnLocationForCompletedJob

http://localhost:44703/DataCleanUp/SetOnLocationProductHaulsChildrenOnLocation

http://localhost:44703/DataCleanUp/SetProductHaulWithoutCallSheetOnLocation

http://localhost:44703/DataCleanUp/SetBlendCompletedProductHaulLoadOnLocationForCompletedJob

http://localhost:44703/DataCleanUp/SetScheduledProductHaulLoadOnLocationForCompletedJob

http://localhost:44703/DataCleanUp/SetScheduledProductHaulOnLocationForOnLocationBlendRequest

http://localhost:44703/DataCleanUp/CleanupProductHaulForADeletedRigRjob

http://localhost:44703/DataCleanUp/DeleteScheduledProductHaulsWithoutShippingLoadSheet