select 
ID as ID, 
'' as SYSTEM_ID,
1 as version, 
LAST_MODIFIED_USER_ID as MODIFIED_USER_ID, 
LAST_MODIFIED_USER_NAME as  MODIFIED_USER_NAME,
case 
	when LAST_MODIFIED_DATE_TIME = CAST('0001-01-01 00:00:00'as DATETIME2)
	THEN CAST('2016-06-01 00:00:00' as DATETIME)
	ELSE CAST(LAST_MODIFIED_DATE_TIME as DATETIME)
End as MODIFIED_DATE_TIME,
LAST_OPERATION_TYPE as OPERATION_TYPE,
case 
	when EFFECTIVE_START_DATE_TIME = CAST('0001-01-01 00:00:00'as DATETIME2)
	THEN CAST('2016-06-01 00:00:00' as DATETIME)
	ELSE CAST(EFFECTIVE_START_DATE_TIME as DATETIME)
End as EFFECTIVE_START_DATETIME,
case 
	when EFFECTIVE_END_DATE_TIME = CAST('0001-01-01 00:00:00'as DATETIME2)
	THEN CAST('2016-06-01 00:00:00' as DATETIME)
	ELSE CAST(EFFECTIVE_END_DATE_TIME as DATETIME)
End as EFFECTIVE_END_DATETIME,
0 as ENTITY_STATUS,
IS_BASE_BLEND_ELIGIBLE as IsBaseEligible,
BLEND_PRI_CAT_ID as BlendPrimaryCategoryId,
BLEND_PRI_CAT_ID as BlendPrimaryCategorySystemId,
IS_THIXOTROPIC as IsThixotropic,
IS_ADDITIVE_ELIGIBLE as IsAdditiveEligible,
BAGSIZE as BagSize,
ADDITIVE_TYPE_ID as AdditiveTypeId,
ADDITIVE_TYPE_ID as AdditiveTypeSystemId,
DESCRIPTION as DESCRIPTION,
DENSITY as Density,
PRODUCT_ID as PRODUCTID,
PRODUCT_ID as ProductSystemId,
YIELD as Yield,
NAME AS NAME,
MIX_WATER As MixWater,
AERCODE as AERCode,
SPECIfIC_GRAVITY as SpecificGravity,
BLEND_RECIPE_ID AS BlendRecipeId,
BLEND_RECIPE_ID AS BlendRecipeSystemId,
BLEND_FLUID_TYPE_ID AS BlendFluidTypeId,
BLEND_FLUID_TYPE_ID AS BlendFluidTypeSystemId
from Blend_chemicals where EFFECTIVE_END_DATE_TIME > GETDATE();