ALTER TABLE [PUMP_BLEND_SCTNS] ADD [BHST] [float] NULL;
ALTER TABLE [PUMP_BLEND_SCTNS] ADD [BHCT] [float] NULL;
ALTER TABLE [PUMP_BLEND_SCTNS] ADD [BOTTOM_DEPTH] [float] NULL;
ALTER TABLE [PUMP_BLEND_SCTNS] ADD [TOP_DEPTH] [float] NULL;

ALTER TABLE [PRG_BLEND_SCTNS] ADD [BHST] [float] NULL;
ALTER TABLE [PRG_BLEND_SCTNS] ADD [BHCT] [float] NULL;
ALTER TABLE [PRG_BLEND_SCTNS] ADD [BOTTOM_DEPTH] [float] NULL;
ALTER TABLE [PRG_BLEND_SCTNS] ADD [TOP_DEPTH] [float] NULL;


ALTER TABLE [PSPT_BLEND_SCTNS] ADD [BHST] [float] NULL;
ALTER TABLE [PSPT_BLEND_SCTNS] ADD [BHCT] [float] NULL;
ALTER TABLE [PSPT_BLEND_SCTNS] ADD [BOTTOM_DEPTH] [float] NULL;
ALTER TABLE [PSPT_BLEND_SCTNS] ADD [TOP_DEPTH] [float] NULL;