--------------------------------------------------------
--  File created - Monday-November-27-2017   
--------------------------------------------------------
REM INSERTING into BIN_TYPES
SET DEFINE OFF;
Insert into BIN_TYPES (ID,DESCRIPTION,VERSION,LAST_MODIFIED_USER_ID,LAST_MODIFIED_USER_NAME,LAST_MODIFIED_DATE_TIME,LAST_OPERATION_TYPE,EFFECTIVE_START_DATE_TIME,EFFECTIVE_END_DATE_TIME) values (7,'P-Tank',1,29747,'awang',to_timestamp('27-NOV-17 01.43.23.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),1,to_date('01-JAN-01','DD-MON-RR'),to_date('31-DEC-99','DD-MON-RR'));
Insert into BIN_TYPES (ID,DESCRIPTION,VERSION,LAST_MODIFIED_USER_ID,LAST_MODIFIED_USER_NAME,LAST_MODIFIED_DATE_TIME,LAST_OPERATION_TYPE,EFFECTIVE_START_DATE_TIME,EFFECTIVE_END_DATE_TIME) values (8,'Mega Silo',1,29747,'awang',to_timestamp('27-NOV-17 01.44.14.000000000 PM','DD-MON-RR HH.MI.SSXFF AM'),1,to_date('01-JAN-01','DD-MON-RR'),to_date('31-DEC-99','DD-MON-RR'));


