set define off

update companies set SHORT_NAME = 'TAQA', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4654;
update companies set SHORT_NAME = 'Grizzly', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2189;
update companies set SHORT_NAME = 'Midale', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3017;
update companies set SHORT_NAME = 'Sanjel', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 9061;
update companies set SHORT_NAME = 'SPRC', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4414;
update companies set SHORT_NAME = 'Manitok', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3116;
update companies set SHORT_NAME = 'Newalta', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3202;
update companies set SHORT_NAME = 'NuVista', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3245;
update companies set SHORT_NAME = 'Northpoint', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3254;
update companies set SHORT_NAME = 'Paramount', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3708;
update companies set SHORT_NAME = 'PennWest', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3712;
update companies set SHORT_NAME = 'Postell', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3722;
update companies set SHORT_NAME = 'Pengrowth', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3756;
update companies set SHORT_NAME = 'Peyto', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3758;
update companies set SHORT_NAME = 'Progress', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3768;
update companies set SHORT_NAME = 'Questerre', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3910;
update companies set SHORT_NAME = 'Rife', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4011;
update companies set SHORT_NAME = 'Rock Energy', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4088;
update companies set SHORT_NAME = 'Sphere', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4244;
update companies set SHORT_NAME = 'Aspenleaf', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1119;
update companies set SHORT_NAME = 'Fort Calgary', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2090;
update companies set SHORT_NAME = 'Cequence', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4424;
update companies set SHORT_NAME = 'Delphi', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1868;
update companies set SHORT_NAME = 'Plains Mid', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3913;
update companies set SHORT_NAME = 'Perpetual', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3814;
update companies set SHORT_NAME = 'Husky', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4008;
update companies set SHORT_NAME = 'Ravens Cross', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4053;
update companies set SHORT_NAME = 'Mancal', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3037;
update companies set SHORT_NAME = 'MEG', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3061;
update companies set SHORT_NAME = 'Advance', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30075;
update companies set SHORT_NAME = 'Akita', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30076;
update companies set SHORT_NAME = 'Beaver', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30081;
update companies set SHORT_NAME = 'Chinook', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30089;
update companies set SHORT_NAME = 'Ensign', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30095;
update companies set SHORT_NAME = 'Excalibur', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30096;
update companies set SHORT_NAME = 'Horizon', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30100;
update companies set SHORT_NAME = 'Jomax', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30104;
update companies set SHORT_NAME = 'Lasso', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30106;
update companies set SHORT_NAME = 'Nabors', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30108;
update companies set SHORT_NAME = 'Panther', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30112;
update companies set SHORT_NAME = 'Quintera', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30115;
update companies set SHORT_NAME = 'Red Dog', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30116;
update companies set SHORT_NAME = 'Tempco', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30123;
update companies set SHORT_NAME = 'Treo', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30128;
update companies set SHORT_NAME = 'Xtreme Coil', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30134;
update companies set SHORT_NAME = 'Prosper', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3878;
update companies set SHORT_NAME = 'Painted Pony', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3884;
update companies set SHORT_NAME = 'RCS', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4144;
update companies set SHORT_NAME = 'Hanna O&G', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2207;
update companies set SHORT_NAME = 'Apache', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1018;
update companies set SHORT_NAME = 'Arc', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1043;
update companies set SHORT_NAME = 'Athena', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1054;
update companies set SHORT_NAME = 'Apache (Zama)', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1101;
update companies set SHORT_NAME = 'Anderson', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1109;
update companies set SHORT_NAME = 'CPEC', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1637;
update companies set SHORT_NAME = 'Cansearch', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1696;
update companies set SHORT_NAME = 'Direct', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1822;
update companies set SHORT_NAME = 'Devon', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1840;
update companies set SHORT_NAME = 'Sinopec', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1875;
update companies set SHORT_NAME = 'Baytex', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1205;
update companies set SHORT_NAME = 'Bonavista', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1226;
update companies set SHORT_NAME = 'Birchcliff', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1322;
update companies set SHORT_NAME = 'PPRC', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1508;
update companies set SHORT_NAME = 'CNRL', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1513;
update companies set SHORT_NAME = 'Conoco', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1537;
update companies set SHORT_NAME = 'Jarrod', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2507;
update companies set SHORT_NAME = 'Vital', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1793;
update companies set SHORT_NAME = 'Shell', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4208;
update companies set SHORT_NAME = 'Insignia', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2444;
update companies set SHORT_NAME = 'Bonterra', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1246;
update companies set SHORT_NAME = 'Cenovus FCCL', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2054;
update companies set SHORT_NAME = 'Athabasca', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1151;
update companies set SHORT_NAME = 'NEP', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3099;
update companies set SHORT_NAME = 'NAL', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3200;
update companies set SHORT_NAME = 'Nexen', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3266;
update companies set SHORT_NAME = 'Yoho', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4908;
update companies set SHORT_NAME = 'Zargon', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 5000;
update companies set SHORT_NAME = 'Spur', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4390;
update companies set SHORT_NAME = 'Abandonrite', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4523;
update companies set SHORT_NAME = 'Vermilion', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4700;
update companies set SHORT_NAME = 'EOG', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1908;
update companies set SHORT_NAME = 'Gryphon', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2173;
update companies set SHORT_NAME = 'Galaxy', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2184;
update companies set SHORT_NAME = 'Harvest', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2242;
update companies set SHORT_NAME = 'Imperial', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2401;
update companies set SHORT_NAME = 'Tristar', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4447;
update companies set SHORT_NAME = 'Advantage', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1084;
update companies set SHORT_NAME = 'Barnwell', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1258;
update companies set SHORT_NAME = 'CCR', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1506;
update companies set SHORT_NAME = 'City of Med Hat', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1583;
update companies set SHORT_NAME = 'Crew', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1689;
update companies set SHORT_NAME = 'Encana', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1946;
update companies set SHORT_NAME = 'ERCO', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1986;
update companies set SHORT_NAME = 'Ember', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1988;
update companies set SHORT_NAME = 'Striker', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1998;
update companies set SHORT_NAME = 'Grizzly', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2161;
update companies set SHORT_NAME = 'Repsol', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4500;
update companies set SHORT_NAME = 'Tundra', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4536;
update companies set SHORT_NAME = 'Craft', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4639;
update companies set SHORT_NAME = 'Aldon', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1040;
update companies set SHORT_NAME = 'Cemeco', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2300;
update companies set SHORT_NAME = 'Tourmaline', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4668;
update companies set SHORT_NAME = 'Benchmark', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1385;
update companies set SHORT_NAME = 'Connaught', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1639;
update companies set SHORT_NAME = 'Spartan', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4439;
update companies set SHORT_NAME = 'Tuscany', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4630;
update companies set SHORT_NAME = 'Keyera', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2644;
update companies set SHORT_NAME = 'Murphy', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3013;
update companies set SHORT_NAME = 'Palliser', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3879;
update companies set SHORT_NAME = 'Crocotta', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1782;
update companies set SHORT_NAME = 'OSUM', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3546;
update companies set SHORT_NAME = 'CCEC', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1765;
update companies set SHORT_NAME = 'MacBain', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 9063;
update companies set SHORT_NAME = 'ISH', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2406;
update companies set SHORT_NAME = 'Brownstone', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1227;
update companies set SHORT_NAME = 'Suncor', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4226;
update companies set SHORT_NAME = 'Endurance', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2307;
update companies set SHORT_NAME = 'BlackPearl', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1389;
update companies set SHORT_NAME = '7Gen', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4458;
update companies set SHORT_NAME = 'Ron Resources', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4166;
update companies set SHORT_NAME = 'Coastal', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1758;
update companies set SHORT_NAME = 'Vale PC', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4841;
update companies set SHORT_NAME = 'Cenovus Energy', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1499;
update companies set SHORT_NAME = 'Legacy', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2763;
update companies set SHORT_NAME = 'Baccelieu', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1394;
update companies set SHORT_NAME = 'JACOS', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2505;
update companies set SHORT_NAME = 'CQ Energy', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4459;
update companies set SHORT_NAME = 'Suncor', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4462;
update companies set SHORT_NAME = 'BLZ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1397;
update companies set SHORT_NAME = 'Kinwest', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2656;
update companies set SHORT_NAME = 'Conserve', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1494;
update companies set SHORT_NAME = 'Fortis', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3109;
update companies set SHORT_NAME = 'Bounty', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1217;
update companies set SHORT_NAME = 'Keystone', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2657;
update companies set SHORT_NAME = 'Renegade', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4167;
update companies set SHORT_NAME = 'Kasten', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2658;
update companies set SHORT_NAME = 'Chinook', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1493;
update companies set SHORT_NAME = 'Surge', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 5001;
update companies set SHORT_NAME = 'Sydco', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4467;
update companies set SHORT_NAME = 'Teine', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4682;
update companies set SHORT_NAME = 'Gain', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3513;
update companies set SHORT_NAME = 'Wold Coulee', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4895;
update companies set SHORT_NAME = 'Edge', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2336;
update companies set SHORT_NAME = 'Broadview', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1406;
update companies set SHORT_NAME = 'Croverro', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1481;
update companies set SHORT_NAME = 'Ravens Cross', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4002;
update companies set SHORT_NAME = 'Kaiser', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2605;
update companies set SHORT_NAME = 'Yangarra', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4905;
update companies set SHORT_NAME = 'JDM', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2501;
update companies set SHORT_NAME = 'Border', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1371;
update companies set SHORT_NAME = 'Alberta Oilsands', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3834;
update companies set SHORT_NAME = 'Inter Pipeline', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2450;
update companies set SHORT_NAME = 'Spur ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4429;
update companies set SHORT_NAME = 'AltaGas ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1163;
update companies set SHORT_NAME = 'Caprice ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1586;
update companies set SHORT_NAME = 'UGR ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4665;
update companies set SHORT_NAME = 'Pembina Pipeline ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3779;
update companies set SHORT_NAME = 'Mosaic ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2137;
update companies set SHORT_NAME = 'Atco ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1085;
update companies set SHORT_NAME = 'Petrex ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3739;
update companies set SHORT_NAME = 'Patterson', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30140;
update companies set SHORT_NAME = 'TORC ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4687;
update companies set SHORT_NAME = 'Whitecap ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4939;
update companies set SHORT_NAME = 'NBR', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3304;
update companies set SHORT_NAME = 'Longview ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2777;
update companies set SHORT_NAME = 'Second Wave ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4487;
update companies set SHORT_NAME = 'Success', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4197;
update companies set SHORT_NAME = 'Marquee ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2998;
update companies set SHORT_NAME = 'Artisan ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1198;
update companies set SHORT_NAME = 'Wyatt ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4941;
update companies set SHORT_NAME = 'Coda ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1461;
update companies set SHORT_NAME = 'Inception ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2395;
update companies set SHORT_NAME = 'Savanna ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30147;
update companies set SHORT_NAME = 'Standard ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4492;
update companies set SHORT_NAME = 'Gear ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2347;
update companies set SHORT_NAME = 'Relentless ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4177;
update companies set SHORT_NAME = 'Tetonka ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4685;
update companies set SHORT_NAME = 'Western Star North', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4936;
update companies set SHORT_NAME = 'Hyak ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2365;
update companies set SHORT_NAME = 'Thru Tubing', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4693;
update companies set SHORT_NAME = 'Kripa ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2661;
update companies set SHORT_NAME = 'Predator ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30148;
update companies set SHORT_NAME = 'Caltex ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1452;
update companies set SHORT_NAME = 'Pinecrest ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3929;
update companies set SHORT_NAME = 'Tangle Creek ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4499;
update companies set SHORT_NAME = 'Potts ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3688;
update companies set SHORT_NAME = 'GroundForce', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2378;
update companies set SHORT_NAME = 'Strategic ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4477;
update companies set SHORT_NAME = 'Direct Energy ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2382;
update companies set SHORT_NAME = 'Red River ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4180;
update companies set SHORT_NAME = 'Grandview ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2385;
update companies set SHORT_NAME = 'Brion ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2387;
update companies set SHORT_NAME = 'Lakeview ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2689;
update companies set SHORT_NAME = 'Bonanza D', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30155;
update companies set SHORT_NAME = 'Dark Warrior', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2391;
update companies set SHORT_NAME = 'Long Run ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2779;
update companies set SHORT_NAME = 'EEML', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2392;
update companies set SHORT_NAME = 'Komat ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30158;
update companies set SHORT_NAME = 'Beaumont ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2487;
update companies set SHORT_NAME = 'Corex ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2462;
update companies set SHORT_NAME = 'Birchill', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2489;
update companies set SHORT_NAME = 'CaiTerra', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2495;
update companies set SHORT_NAME = 'Bering ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2496;
update companies set SHORT_NAME = 'Villanova ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 4788;
update companies set SHORT_NAME = 'Gibson ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2559;
update companies set SHORT_NAME = 'Consumers Co-op', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 1541;
update companies set SHORT_NAME = 'Enerplus ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 2338;
update companies set SHORT_NAME = 'Nordegg ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 3303;
update companies set SHORT_NAME = 'RMP ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30265;
update companies set SHORT_NAME = 'North 40 ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30266;
update companies set SHORT_NAME = 'TransGlobe', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30267;
update companies set SHORT_NAME = 'Ox Energy ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30268;
update companies set SHORT_NAME = 'Suncor E&P', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30269;
update companies set SHORT_NAME = 'High Ground ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30270;
update companies set SHORT_NAME = 'West Lake ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30271;
update companies set SHORT_NAME = 'Silver Bay ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30272;
update companies set SHORT_NAME = 'Agrium Potash', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30273;
update companies set SHORT_NAME = 'ProFoxx ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30274;
update companies set SHORT_NAME = 'Yaletown ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30276;
update companies set SHORT_NAME = 'Point Loma ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30277;
update companies set SHORT_NAME = 'Saturn ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30278;
update companies set SHORT_NAME = 'Sun Century', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30279;
update companies set SHORT_NAME = 'HRML', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30280;
update companies set SHORT_NAME = 'Windward', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30281;
update companies set SHORT_NAME = 'Fortune ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30282;
update companies set SHORT_NAME = 'Alta Crete ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30283;
update companies set SHORT_NAME = 'McLand ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30284;
update companies set SHORT_NAME = 'Bertram ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30229;
update companies set SHORT_NAME = 'Stewart ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30230;
update companies set SHORT_NAME = 'Novus ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30231;
update companies set SHORT_NAME = 'Tidewater ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30233;
update companies set SHORT_NAME = 'Tervita', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30234;
update companies set SHORT_NAME = 'Ridgeback', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30235;
update companies set SHORT_NAME = 'Serafina ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30236;
update companies set SHORT_NAME = 'Triple 5', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30238;
update companies set SHORT_NAME = 'C-FER ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30239;
update companies set SHORT_NAME = 'NCS ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30240;
update companies set SHORT_NAME = 'Pemoco', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30241;
update companies set SHORT_NAME = 'Capio ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30242;
update companies set SHORT_NAME = 'Cenovus TL ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30243;
update companies set SHORT_NAME = 'Burgess Creek ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30244;
update companies set SHORT_NAME = 'Courage ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30245;
update companies set SHORT_NAME = 'Hunter ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30246;
update companies set SHORT_NAME = 'Entrada ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30247;
update companies set SHORT_NAME = 'Persta ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30248;
update companies set SHORT_NAME = 'Pipestone ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30249;
update companies set SHORT_NAME = 'Nsolv ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30250;
update companies set SHORT_NAME = 'Charles Taylor ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30251;
update companies set SHORT_NAME = 'Mac Energy ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30252;
update companies set SHORT_NAME = 'Tiger ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30253;
update companies set SHORT_NAME = 'Mark Dimler', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30254;
update companies set SHORT_NAME = 'Allstar', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30255;
update companies set SHORT_NAME = 'Steelhead ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30256;
update companies set SHORT_NAME = 'TimberRock ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30257;
update companies set SHORT_NAME = 'PD', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10203;
update companies set SHORT_NAME = 'Prairie Storm ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30258;
update companies set SHORT_NAME = 'Fort Hills ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30259;
update companies set SHORT_NAME = 'Lonquist ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30260;
update companies set SHORT_NAME = 'CEC Northstar', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30261;
update companies set SHORT_NAME = 'Halo', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10214;
update companies set SHORT_NAME = 'Fox ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30169;
update companies set SHORT_NAME = 'Modern ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30262;
update companies set SHORT_NAME = 'Summerland ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30263;
update companies set SHORT_NAME = 'Artisan ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10218;
update companies set SHORT_NAME = 'Weil Group ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30264;
update companies set SHORT_NAME = 'Ventura', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30193;
update companies set SHORT_NAME = 'Deltastream ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30199;
update companies set SHORT_NAME = 'NAH', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30196;
update companies set SHORT_NAME = 'Audax ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30197;
update companies set SHORT_NAME = 'Hemisphere ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30198;
update companies set SHORT_NAME = 'Petrus', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10231;
update companies set SHORT_NAME = 'Mountain', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30200;
update companies set SHORT_NAME = 'Savanna ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30201;
update companies set SHORT_NAME = 'Peaceland ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30202;
update companies set SHORT_NAME = 'ExxonMobil ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30204;
update companies set SHORT_NAME = 'DCP', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30205;
update companies set SHORT_NAME = 'Hummingbird ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30206;
update companies set SHORT_NAME = 'Altura ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30207;
update companies set SHORT_NAME = 'Rampart', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30208;
update companies set SHORT_NAME = 'AOC Hangingstone ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10243;
update companies set SHORT_NAME = 'Taku ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10244;
update companies set SHORT_NAME = 'Avalon ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30209;
update companies set SHORT_NAME = 'Lehigh ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30210;
update companies set SHORT_NAME = 'Kingsland ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10247;
update companies set SHORT_NAME = 'Kelt (LNG)', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30211;
update companies set SHORT_NAME = 'Star Valley ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30212;
update companies set SHORT_NAME = 'Quinn ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30213;
update companies set SHORT_NAME = 'Twilight ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30214;
update companies set SHORT_NAME = 'Westbrick', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10252;
update companies set SHORT_NAME = 'CWC', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30215;
update companies set SHORT_NAME = 'Citadel ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30216;
update companies set SHORT_NAME = 'Betts', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30217;
update companies set SHORT_NAME = 'Vortex ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30218;
update companies set SHORT_NAME = 'Praxair S', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10257;
update companies set SHORT_NAME = 'D2 ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30219;
update companies set SHORT_NAME = 'STEP ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30221;
update companies set SHORT_NAME = 'NOVA', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30222;
update companies set SHORT_NAME = 'Cordy ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10262;
update companies set SHORT_NAME = 'Turnstone ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30223;
update companies set SHORT_NAME = 'City of Med Hat', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30224;
update companies set SHORT_NAME = 'Gambit', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30225;
update companies set SHORT_NAME = 'Gensource', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30226;
update companies set SHORT_NAME = 'Mosaic Potash ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30227;
update companies set SHORT_NAME = 'Chemtrade ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30228;
update companies set SHORT_NAME = 'Andora ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10269;
update companies set SHORT_NAME = 'Elrose', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10272;
update companies set SHORT_NAME = 'Secure ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10276;
update companies set SHORT_NAME = 'Encore ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10285;
update companies set SHORT_NAME = 'Altagas ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10282;
update companies set SHORT_NAME = 'Canadian Coyote ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10283;
update companies set SHORT_NAME = '1316751 Alberta ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10287;
update companies set SHORT_NAME = 'Nexxco ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10288;
update companies set SHORT_NAME = 'Bernum', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10289;
update companies set SHORT_NAME = 'RPCL', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10290;
update companies set SHORT_NAME = 'Blaze', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10293;
update companies set SHORT_NAME = 'Dreco ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10294;
update companies set SHORT_NAME = 'Nextraction E', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10300;
update companies set SHORT_NAME = 'Frontier ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10296;
update companies set SHORT_NAME = 'Raging River ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10302;
update companies set SHORT_NAME = 'Alliance ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30177;
update companies set SHORT_NAME = 'Beringer ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10304;
update companies set SHORT_NAME = 'BDJ ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10307;
update companies set SHORT_NAME = 'Spry2', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10308;
update companies set SHORT_NAME = 'Grassy Hill', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10312;
update companies set SHORT_NAME = 'Ouro Preto ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10314;
update companies set SHORT_NAME = 'ORLEN ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10316;
update companies set SHORT_NAME = 'RockEast ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10321;
update companies set SHORT_NAME = 'Elcano', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10322;
update companies set SHORT_NAME = 'Losness ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10323;
update companies set SHORT_NAME = 'MacKay ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10324;
update companies set SHORT_NAME = 'Blackspur ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10325;
update companies set SHORT_NAME = 'Hitic', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10326;
update companies set SHORT_NAME = 'Oak Point', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10328;
update companies set SHORT_NAME = 'Venturion ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10333;
update companies set SHORT_NAME = 'Aqua North ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10340;
update companies set SHORT_NAME = 'Velvet', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10344;
update companies set SHORT_NAME = 'Black Swan', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10355;
update companies set SHORT_NAME = 'Freemont ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10357;
update companies set SHORT_NAME = 'Kelt ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10360;
update companies set SHORT_NAME = 'Alder Ridge ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10361;
update companies set SHORT_NAME = 'Highmark ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10364;
update companies set SHORT_NAME = '1764821 Alberta ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10365;
update companies set SHORT_NAME = 'Spyglass ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10366;
update companies set SHORT_NAME = 'Regco ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10367;
update companies set SHORT_NAME = 'XTO ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10369;
update companies set SHORT_NAME = 'Four Winds ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10371;
update companies set SHORT_NAME = 'Paradise', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10372;
update companies set SHORT_NAME = 'Triland', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10373;
update companies set SHORT_NAME = 'Major Oil ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10374;
update companies set SHORT_NAME = 'Blackbird', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10376;
update companies set SHORT_NAME = 'CQEC', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10377;
update companies set SHORT_NAME = 'Western Union ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10387;
update companies set SHORT_NAME = 'Ikkuma', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10385;
update companies set SHORT_NAME = 'DragonFountain', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10388;
update companies set SHORT_NAME = 'Potash Corp', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10391;
update companies set SHORT_NAME = 'New Star ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10392;
update companies set SHORT_NAME = 'Mobius ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10393;
update companies set SHORT_NAME = 'EverGro ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10395;
update companies set SHORT_NAME = 'Fire Creek ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10396;
update companies set SHORT_NAME = 'Caprock ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10397;
update companies set SHORT_NAME = 'Inplay ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10398;
update companies set SHORT_NAME = 'Sahara ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10399;
update companies set SHORT_NAME = 'Leucrotta', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10400;
update companies set SHORT_NAME = 'Bruin ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10402;
update companies set SHORT_NAME = 'Cardinal ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10403;
update companies set SHORT_NAME = 'WAJAX ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10405;
update companies set SHORT_NAME = 'Corval ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10406;
update companies set SHORT_NAME = 'Knowledge', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10409;
update companies set SHORT_NAME = 'Response', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10411;
update companies set SHORT_NAME = 'WSP ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10419;
update companies set SHORT_NAME = 'Riflemen ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10420;
update companies set SHORT_NAME = 'K+S', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10421;
update companies set SHORT_NAME = 'Shiningstar ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10429;
update companies set SHORT_NAME = 'Sitka ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10432;
update companies set SHORT_NAME = 'Crusader ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30183;
update companies set SHORT_NAME = 'NVP', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10434;
update companies set SHORT_NAME = 'Scavenger ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10435;
update companies set SHORT_NAME = 'Koch ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10438;
update companies set SHORT_NAME = 'Indepth ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10439;
update companies set SHORT_NAME = 'Steppe ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10441;
update companies set SHORT_NAME = 'Mapan ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10442;
update companies set SHORT_NAME = 'Birchill ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10443;
update companies set SHORT_NAME = 'Term Oil ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10447;
update companies set SHORT_NAME = 'Flushing', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10453;
update companies set SHORT_NAME = 'Melita ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10454;
update companies set SHORT_NAME = 'Steel Reef ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10455;
update companies set SHORT_NAME = 'Spectrum', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10456;
update companies set SHORT_NAME = 'Serafina ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10459;
update companies set SHORT_NAME = 'Cross Borders ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10460;
update companies set SHORT_NAME = 'Trinidad ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10463;
update companies set SHORT_NAME = 'Mosaic (Est)', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10467;
update companies set SHORT_NAME = '1894078 Alberta ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10471;
update companies set SHORT_NAME = 'Tamarack ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10472;
update companies set SHORT_NAME = 'Stampede ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30184;
update companies set SHORT_NAME = 'Sirius', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30185;
update companies set SHORT_NAME = 'Enhance ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10474;
update companies set SHORT_NAME = 'Jupiter ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10475;
update companies set SHORT_NAME = 'EnvolveE', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10477;
update companies set SHORT_NAME = 'Freehold ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10478;
update companies set SHORT_NAME = 'Shield', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10481;
update companies set SHORT_NAME = 'Toro ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10483;
update companies set SHORT_NAME = 'Peaceland ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10488;
update companies set SHORT_NAME = 'Virginia Hills ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10492;
update companies set SHORT_NAME = 'Altabras', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10497;
update companies set SHORT_NAME = 'AOC Kaybob ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10498;
update companies set SHORT_NAME = 'Catapult ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10502;
update companies set SHORT_NAME = 'Questfire ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10503;
update companies set SHORT_NAME = 'AOC Simonette ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10507;
update companies set SHORT_NAME = 'Hawk ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10510;
update companies set SHORT_NAME = 'Glenogle ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10514;
update companies set SHORT_NAME = 'HESC ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10515;
update companies set SHORT_NAME = 'ISCL', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10516;
update companies set SHORT_NAME = 'AOC Grande Prairie', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10523;
update companies set SHORT_NAME = 'Forge ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10530;
update companies set SHORT_NAME = 'Crossing Company', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10533;
update companies set SHORT_NAME = 'Groundstar ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10534;
update companies set SHORT_NAME = 'Todd', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10545;
update companies set SHORT_NAME = 'Rocky River', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10547;
update companies set SHORT_NAME = 'DC ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30188;
update companies set SHORT_NAME = 'Nytis ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10548;
update companies set SHORT_NAME = 'Mutiny ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10549;
update companies set SHORT_NAME = 'R Batke ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10553;
update companies set SHORT_NAME = 'Canyon ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10554;
update companies set SHORT_NAME = 'Octane ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10561;
update companies set SHORT_NAME = 'Martin Brower ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10566;
update companies set SHORT_NAME = 'Recem', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10567;
update companies set SHORT_NAME = 'Ribbon Creek ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10568;
update companies set SHORT_NAME = 'Ledcor ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10570;
update companies set SHORT_NAME = 'Polar Star ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10571;
update companies set SHORT_NAME = 'Rally ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10576;
update companies set SHORT_NAME = 'G P Masonry ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10578;
update companies set SHORT_NAME = 'Baytech ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10579;
update companies set SHORT_NAME = 'Duracon ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10581;
update companies set SHORT_NAME = 'Granite', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 10583;
update companies set SHORT_NAME = 'Boulder', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30189;
update companies set SHORT_NAME = 'Goldenkey ', version=version+1, LAST_MODIFIED_DATE_TIME=sysdate where id = 30192;