
select count(*) from CALLSHEET_HEADERS;

select count(distinct CSH.CALL_SHEET_NUMBER) from CALLSHEET_HEADERS CSH
Join rigs RIG on CSH.WLI_RIG_COMPANY_ID = RIG.DRILLINGCOMPANY_ID and CSH.WLI_RIG_NUM = RIG.RIG_NO;

update CALLSHEET_HEADERS CSH set WLI_RIG_ID = (select id from rigs RIG where CSH.WLI_RIG_COMPANY_ID = RIG.DRILLINGCOMPANY_ID and CSH.WLI_RIG_NUM = RIG.RIG_NO), 
CSH.WLI_RIG_NAME = (select name from rigs RIG where CSH.WLI_RIG_COMPANY_ID = RIG.DRILLINGCOMPANY_ID and CSH.WLI_RIG_NUM = RIG.RIG_NO);