CREATE TABLE ESERVICE3.RIG_JOB
(
  ID                         NUMBER(10),
  JOB_ALERT_ID               NUMBER(10),
  CALL_SHEET_NUMBER          NUMBER(10),
  JOB_UNIQUE_ID              VARCHAR2(20 BYTE),
  NOTES                      VARCHAR2(500 BYTE),
  PROGRAM_ID                 VARCHAR2(20 BYTE),
  JOB_LIFE_STATUS            NUMBER(6),
  VERSION                    NUMBER(6)          DEFAULT 0,
  LAST_MODIFIED_USER_ID      NUMBER(10)         DEFAULT 0,
  LAST_MODIFIED_USER_NAME    VARCHAR2(150 BYTE) DEFAULT '',
  LAST_MODIFIED_DATE_TIME    TIMESTAMP(9)       DEFAULT SYSTIMESTAMP          NOT NULL,
  LAST_OPERATION_TYPE        NUMBER(5)          DEFAULT 0,
  EFFECTIVE_START_DATE_TIME  DATE               DEFAULT TO_DATE('01-JAN-0001', 'DD-MON-YYYY'),
  EFFECTIVE_END_DATE_TIME    DATE               DEFAULT TO_DATE('31-DEC-9999', 'DD-MON-YYYY') NOT NULL
)
TABLESPACE USERS_ESERVICE3
PCTUSED    40
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            FREELISTS        1
            FREELIST GROUPS  1
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
MONITORING;


CREATE UNIQUE INDEX ESERVICE3.PRIG_JOB_ID_PK ON ESERVICE3.RIG_JOB
(ID)
LOGGING
TABLESPACE USERS_ESERVICE3_IDX
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           );

ALTER TABLE ESERVICE3.RIG_JOB ADD (
  CONSTRAINT RIG_JOB_ID_PK
  PRIMARY KEY
  (ID)
  USING INDEX ESERVICE3.RIG_JOB_ID_PK
  ENABLE VALIDATE);

  CREATE SEQUENCE ESERVICE3.SEQ_RIG_JOB
  START WITH 50
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
  commit;
  
  -- 2017/11/27 Adam: Add rig reference to rig job
  
  alter table RIG_JOB add (RIG_ID NUMBER(10));
  alter table RIG_JOB add (DRILLINGCOMPNAY_ID NUMBER(10));
  alter table RIG_JOB add (RIG_NAME VARCHAR2(50 BYTE));
  alter table RIG_JOB add (JOB_DATE_TIME DATE);
  alter table RIG_JOB add (WELL_LOCATION VARCHAR2(100 BYTE));
  alter table RIG_JOB add (WELL_LOCATION_TYPE_ID NUMBER(10,0));
  alter table RIG_JOB add (WELL_LOCATION_TYPE_NAME VARCHAR2(50 BYTE));
  alter table RIG_JOB add (IS_DOWNHOLE_LOCATION NUMBER(1));
  
  -- 2017/11/29 Adam: Add rig reference to rig job

  alter table RIG_JOB add (CLIENT_COMPANY_ID NUMBER(10));
  alter table RIG_JOB add (CLIENT_COMPANY_SHORTNAME VARCHAR2(200 BYTE));

  alter table RIG_JOB add (JOB_TYPE_ID NUMBER(10));
  alter table RIG_JOB add (JOB_TYPE_NAME VARCHAR2(200 BYTE));
  
  alter table RIG_JOB add (SERVICE_POINT_ID NUMBER(10));
  alter table RIG_JOB add (SERVICE_POINT_NAME VARCHAR2(200 BYTE));
  
  alter table RIG_JOB add (IS_LISTED NUMBER(1));
  alter table RIG_JOB add (IS_HIGH_PROFILE_JOB NUMBER(1));

  
  
 -- 2017/11/17  new sql after update, modified the job_unique_id width
 
 CREATE TABLE "ESERVICE3"."RIG_JOB" 
   (	"ID" NUMBER(10,0), 
	"JOB_ALERT_ID" NUMBER(10,0), 
	"CALL_SHEET_NUMBER" NUMBER(10,0), 	
	"JOB_UNIQUE_ID" VARCHAR2(100 BYTE),	
	"NOTES" VARCHAR2(500 BYTE), 
	"PROGRAM_ID" VARCHAR2(20 BYTE), 
	"JOB_LIFE_STATUS" NUMBER(6,0), 
	
	"RIG_ID" NUMBER(10,0), 
	"DRILLINGCOMPNAY_ID" NUMBER(10,0), 
	"RIG_NAME" VARCHAR2(50 BYTE), 
	"JOB_DATE_TIME" DATE, 
	"WELL_LOCATION" VARCHAR2(100 BYTE), 
	"WELL_LOCATION_TYPE_ID" NUMBER(10,0), 
	"WELL_LOCATION_TYPE_NAME" VARCHAR2(50 BYTE), 
	"IS_DOWNHOLE_LOCATION" NUMBER(1,0), 
	
	"CLIENT_COMPANY_ID" NUMBER(10,0), 
	"CLIENT_COMPANY_SHORTNAME" VARCHAR2(50 BYTE), 
	"JOB_TYPE_ID" NUMBER(10,0), 
	"JOB_TYPE_NAME" VARCHAR2(200 BYTE), 
	"SERVICE_POINT_ID" NUMBER(10,0), 
	"SERVICE_POINT_NAME" VARCHAR2(200 BYTE), 
	"IS_HIGH_PROFILE_JOB" NUMBER(1,0),
 	"IS_LISTED" NUMBER(1,0),
	
	"VERSION" NUMBER(6,0) DEFAULT 0, 
	"LAST_MODIFIED_USER_ID" NUMBER(10,0) DEFAULT 0, 
	"LAST_MODIFIED_USER_NAME" VARCHAR2(150 BYTE) DEFAULT '', 
	"LAST_MODIFIED_DATE_TIME" TIMESTAMP (9) DEFAULT SYSTIMESTAMP NOT NULL ENABLE, 
	"LAST_OPERATION_TYPE" NUMBER(5,0) DEFAULT 0, 
	"EFFECTIVE_START_DATE_TIME" DATE DEFAULT TO_DATE('01-JAN-0001', 'DD-MON-YYYY'), 
	"EFFECTIVE_END_DATE_TIME" DATE DEFAULT TO_DATE('31-DEC-9999', 'DD-MON-YYYY') NOT NULL ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS_ESERVICE3" ;

  CREATE UNIQUE INDEX "ESERVICE3"."PRIG_JOB_ID_PK" ON "ESERVICE3"."RIG_JOB" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS_ESERVICE3_IDX" ;

-- 2017/11/17  Bright
  
	alter table RIG_JOB add (CALL_SHEET_ID NUMBER(10)); 
	alter table RIG_JOB add (IS_COD_CLEARED NUMBER(1));
	alter table RIG_JOB add (IS_NEED_BIN NUMBER(1));
	alter table RIG_JOB add (DIRECTION VARCHAR2(1000 BYTE));
	alter table RIG_JOB add (CLIENT_CONSULTANT1_ID NUMBER(10)); 
	alter table RIG_JOB add (CLIENT_CONSULTANT1_NAME VARCHAR2(100 BYTE));
	alter table RIG_JOB add (CLIENT_CONSULTANT1_CELL VARCHAR2(20 BYTE));
	alter table RIG_JOB add (CLIENT_CONSULTANT2_ID NUMBER(10)); 
	alter table RIG_JOB add (CLIENT_CONSULTANT2_NAME VARCHAR2(100 BYTE));
	alter table RIG_JOB add (CLIENT_CONSULTANT2_CELL VARCHAR2(20 BYTE));
	alter table RIG_JOB add (RIG_IS_TOP_DRIVE NUMBER(1)); 
	alter table RIG_JOB add (CC_IS_COD_CUSTOMER NUMBER(1) DEFAULT 0); 