  CREATE TABLE "ESERVICE3"."RIGS" 
   (	"ID" NUMBER(10,0), 
	"NAME" VARCHAR2(100 BYTE), 
	"RIG_NO" VARCHAR2(50 BYTE), 
	"DRILLINGCOMPANY_ID" NUMBER(10,0), 
	"DRILLINGCOMPANY_NAME" VARCHAR2(100 BYTE), 
	"STATUS" NUMBER(6,0), 
	"IS_SERVICE_RIG" NUMBER(1,0), 
	"IS_DELETED" NUMBER(1,0), 
	"IS_TOP_DRIVE" NUMBER(1,0), 
	"SIZE_TYPE_VALUE" NUMBER(10,3), 
	"SIZE_TYPE_UNIT" VARCHAR2(50 BYTE), 
	"RIG_SIZE_TYPE_ID" NUMBER(10,0), 
	"RIG_SIZE_TYPE_NAME" VARCHAR2(50 BYTE), 
	"THREAD_TYPE_ID" NUMBER(10,0), 
	"THREAD_TYPE_NAME" VARCHAR2(50 BYTE), 
	"VERSION" NUMBER(6,0) DEFAULT 0, 
	"LAST_MODIFIED_USER_ID" NUMBER(10,0) DEFAULT 0, 
	"LAST_MODIFIED_USER_NAME" VARCHAR2(150 BYTE) DEFAULT '', 
	"LAST_MODIFIED_DATE_TIME" TIMESTAMP (9) DEFAULT SYSTIMESTAMP, 
	"LAST_OPERATION_TYPE" NUMBER(5,0) DEFAULT 0, 
	"EFFECTIVE_START_DATE_TIME" DATE DEFAULT TO_DATE('01-JAN-0001', 'DD-MON-YYYY'), 
	"EFFECTIVE_END_DATE_TIME" DATE DEFAULT TO_DATE('31-DEC-9999', 'DD-MON-YYYY')
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS_ESERVICE3" ;

CREATE SEQUENCE ESERVICE3.SEQ_RIGS
 START WITH 500
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;