update CALLSHEET_HEADERS CSH set WLI_RIG_ID = (select id from rigs RIG where CSH.WLI_RIG_COMPANY_ID = RIG.DRILLINGCOMPANY_ID and CSH.WLI_RIG_NUM = RIG.RIG_NO), 
CSH.WLI_RIG_NAME = (select name from rigs RIG where CSH.WLI_RIG_COMPANY_ID = RIG.DRILLINGCOMPANY_ID and CSH.WLI_RIG_NUM = RIG.RIG_NO);
