delete from JOBS where LAST_MODIFIED_DATE_TIME < '2019-09-01';

delete from SERVICE_TICKETS where LAST_MODIFIED_DATE_TIME < '2019-09-01';

delete from SERVICE_REPORT_HEADERS where LAST_MODIFIED_DATE_TIME < '2019-09-01';

delete from CALLSHEET_HEADERS where LAST_MODIFIED_DATE_TIME < '2019-09-01';

delete from PROGRAMS where LAST_MODIFIED_DATE_TIME < '2019-09-01';


select top(10) * from SERVICE_TICKETS order by id desc;



ALTER TABLE [dbo].[PRG_CHRG_MTHD_DSCT_SCTNS]  WITH CHECK ADD  CONSTRAINT [PRG_CHRG_MTHD_DSCT_PRG_ID_FK] FOREIGN KEY([PARENT_ID])
REFERENCES [dbo].[PROGRAMS] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PRG_COMPANY_INFO_SCTNS]  WITH CHECK ADD  CONSTRAINT [PRG_COM_INFO_SCTNS_PRG_ID_FK] FOREIGN KEY([ROOT_ID])
REFERENCES [dbo].[PROGRAMS] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].PRG_EMPLOYEE_SCTNS  WITH CHECK ADD  CONSTRAINT PRG_EMPLOYEE_SCTNS_PRG_ID_FK FOREIGN KEY([PARENT_ID])
REFERENCES [dbo].[PROGRAMS] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PRG_GROUP_LINE_ITEM_SCTNS]  WITH CHECK ADD  CONSTRAINT [PRG_GROUP_LINE_ITEM_PRG_ID_FK] FOREIGN KEY([ROOT_ID])
REFERENCES [dbo].[PROGRAMS] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PRG_LINE_ITEM_SCTNS]  WITH CHECK ADD  CONSTRAINT [PRG_LINE_ITEM_PRG_ID_FK] FOREIGN KEY([ROOT_ID])
REFERENCES [dbo].[PROGRAMS] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO

ALTER TABLE [dbo].[PRG_PUMPING_JOB_SECTIONS]  WITH CHECK ADD  CONSTRAINT [PRG_PUMP_JS_PRG_ID_FK] FOREIGN KEY([ROOT_ID])
REFERENCES [dbo].[PROGRAMS] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO


ALTER TABLE [dbo].[PRG_DOWNHOLE_TOOL_SCTNS]  WITH CHECK ADD  CONSTRAINT [PRG_DNHL_TOOL_SCTNS_PRG_JS_ID_FK] FOREIGN KEY([PARENT_ID])
REFERENCES [dbo].[PRG_PUMPING_JOB_SECTIONS] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO


ALTER TABLE [dbo].[PRG_PIPES_SCTNS]  WITH CHECK ADD  CONSTRAINT [PRG_PIPES_SCTNS_PRG_JS_ID_FK] FOREIGN KEY([PARENT_ID])
REFERENCES [dbo].[PRG_PUMPING_JOB_SECTIONS] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO


ALTER TABLE [dbo].[PRG_OPEN_HOLE_SCTNS]  WITH CHECK ADD  CONSTRAINT [PRG_OPEN_HOLE_SCTNS_PRG_IS_ID_FK] FOREIGN KEY([PARENT_ID])
REFERENCES [dbo].[PRG_PUMPING_JOB_SECTIONS] ([ID])
ON UPDATE CASCADE
ON DELETE CASCADE
GO
