ALTER TABLE [CSH_COMPANY_INFO_SCTNS] ADD [IS_TO_BE_INVOICED] [bit] NULL;
ALTER TABLE [JB_COMPANY_INFO_SCTNS] ADD [IS_TO_BE_INVOICED] [bit] NULL;
ALTER TABLE [PRG_COMPANY_INFO_SCTNS] ADD [IS_TO_BE_INVOICED] [bit] NULL;

Update CSH_COMPANY_INFO_SCTNS set IS_TO_BE_INVOICED = IS_CLIENT;
Update CSH_COMPANY_INFO_SCTNS set IS_CLIENT = 1 where COMPANY_TYPE_ID = 1;

Update [JB_COMPANY_INFO_SCTNS] set IS_TO_BE_INVOICED = IS_CLIENT;
Update [JB_COMPANY_INFO_SCTNS] set IS_CLIENT = 1 where COMPANY_TYPE_ID = 1;

Update [PRG_COMPANY_INFO_SCTNS] set IS_TO_BE_INVOICED = IS_CLIENT;
Update [PRG_COMPANY_INFO_SCTNS] set IS_CLIENT = 1 where COMPANY_TYPE_ID = 1;

Update CSH_COMPANY_INFO_SCTNS set IS_CLIENT = 0 where COMPANY_TYPE_ID = 2;
Update [JB_COMPANY_INFO_SCTNS] set IS_CLIENT = 0 where COMPANY_TYPE_ID = 2;
Update [PRG_COMPANY_INFO_SCTNS] set IS_CLIENT = 0 where COMPANY_TYPE_ID = 2;

-- ProductHaul Enhancement release

ALTER TABLE [PUMP_BLEND_SCTNS] ADD [IS_CLIENT_APPROVAL_REQUIRED] [bit] NULL;
ALTER TABLE [PSPT_BLEND_SCTNS] ADD [IS_CLIENT_APPROVAL_REQUIRED] [bit] NULL;
ALTER TABLE [PRG_BLEND_SCTNS] ADD [IS_CLIENT_APPROVAL_REQUIRED] [bit] NULL;

-- Find out last id 
Select * from [dbo].[SD_PERMISSIONS] order by id desc;
-- Add Bulk Plant Board Permission
INSERT [dbo].[SD_PERMISSIONS] ([ID], [APPLICATION_ID], [NAME], [DESCRIPTION], [VERSION]) VALUES (xxxxxx, 572, N'BulkPlantJobViewModel_Bin', N'Online Context Menu: Bulk Plant Board, Bin Column', 0)
GO
-- replace xxxxxx by id from above insert
INSERT [dbo].[SD_GROUP_PERMISSIONS] ([GROUP_ID], [PERMISSION_ID], [VERSION]) VALUES (1000481, xxxxxx, 0)
GO

INSERT [dbo].[SD_PERMISSIONS] ([ID], [APPLICATION_ID], [NAME], [DESCRIPTION], [VERSION]) VALUES (xxxxxx, 572, N'RigJobViewModel_Bin', N'Online Context Menu: Rig Job Board, Bin Column', 0)
GO
-- replace xxxxxx by id from above insert
INSERT [dbo].[SD_GROUP_PERMISSIONS] ([GROUP_ID], [PERMISSION_ID], [VERSION]) VALUES (1000481, xxxxxx, 0)
GO
